#!/usr/bin/perl -w

use strict ;
use warnings ;


# Script destiné au traitement préalable des textes numérisés latins courants
# pour leur traitement par tree-tagger, dans le cadre
# des paramètres définis par le groupe OMNIA
# AG RA 2011-2014  licence GPL 3

# Le script prend en argument les fichiers à tokeniser et, pour chaque fichier,
# insère le résultat dans un fichier portant le même nom, et le préfixe 'token_'
# Usage : tokenizelat-5b.pl fichier1 fichier2 fichier3
# Génère : token_fichier1 token_fichier2 token_fichier3

use utf8 ;
use open ':utf8' ;
use File::Basename;

# Les trois variables ci-dessous ($blocsAE, $blocsOE, $blocsQUE) contiennent la liste
# des mots que nous affichons sans modification (respectivement pas de réduction de la
# diphtongue pour ae et oe, et pas de séparation du -que final).

my $blocsAE = qr/^(?:aer|aere|aerem|aeres|aeri|aeribus|aeris|aerum|anchorae|arnelae|baerna|baernam|baernarum|baernas|baerne|baernis|carae|chae|clae|contraeam|contraeamus|contraeant|contraeas|contraeat|contraeatis|contraeo|contraeundi|contraeundo|contraeundum|contraeunt|contraeunte|contraeuntem|contraeuntes|contraeunti|contraeuntia|contraeuntibus|contraeuntis|contraeuntium|enelaea|enelaei|enelaeis|enelaeo|enelaeorum|enelaeum|escae|escaeam|escaeamus|escaeant|escaeas|escaeat|escaeatis|escaemini|escaentia|escaentiam|escaentiarum|escaentias|escaentie|escaentiis|escaeo|escaere|escaerem|escaeremini|escaeremur|escaeremus|escaerent|escaerentur|escaerer|escaereris|escaeres|escaeret|escaeretis|escaeretur|escaeris|escaeundi|escaeundo|escaeundum|escaeunt|escaeunte|escaeuntem|escaeuntes|escaeunti|escaeuntia|escaeuntibus|escaeuntis|escaeuntium|extraeam|extraeamus|extraeant|extraeas|extraeat|extraeatis|extraeo|extraeria|extraeriam|extraeriarum|extraerias|extraerie|extraeriis|extraeundi|extraeundo|extraeundum|extraeunt|extraeunte|extraeuntem|extraeuntes|extraeunti|extraeuntia|extraeuntibus|extraeuntis|extraeuntium|fraella|fraelli|fraellis|fraello|fraellorum|fraellum|haliaete|haliaeti|haliaetis|haliaeto|haliaeton|haliaetorum|haliaetos|haliaetum|haliaetus|logaedica|logaedicam|logaedicarum|logaedicas|logaedice|logaedicentior|logaedicentiore|logaedicentiorem|logaedicentiores|logaedicentiori|logaedicentioribus|logaedicentioris|logaedicentiorum|logaedicentissima|logaedicentissimam|logaedicentissimarum|logaedicentissimas|logaedicentissime|logaedicentissimi|logaedicentissimis|logaedicentissimo|logaedicentissimorum|logaedicentissimos|logaedicentissimum|logaedicentissimus|logaedici|logaediciora|logaediciore|logaediciori|logaedicioribus|logaedicioris|logaediciorum|logaedicis|logaedicius|logaedico|logaedicorum|logaedicos|logaedicum|logaedicus|manae|melanaete|melanaeti|melanaetis|melanaeto|melanaeton|melanaetorum|melanaetos|nicolae|octaedron|octaedros|octaeteri|octaeteride|octaeteridem|octaeterides|octaeteridi|octaeteridibus|octaeteridis|octaeteridum|octaeteris|praegia|praegii|praegiis|praegio|praegiorum|praegium|praella|praelli|praellis|praello|praellorum|praellum|praeria|praeriam|praeriarum|praerias|praerie|praeriis|pronae|proquaestore|saettia|saettiam|saettiarum|saettias|saettie|saettiis|sculdae|sculdaem|sculdaes|tae|tetraeteri|tetraeteride|tetraeteridem|tetraeterides|tetraeteridi|tetraeteridibus|tetraeteridis|tetraeteridum|tetraeteris|israel|israelita|israelitam|israelite|israelitas|israelitarum|israelitis|israeliticus|israelitice|israeliticum|israelitici|israelitico|israeliticos|israeliticorum|israeliticis|israelitica|israeliticam|israeliticas|israeliticarum|contraeundus|contraeunde|contraeundos|contraeundorum|contraeundis|contraeunda|contraeundam|contraeundas|contraeundarum|contraeuntur|contraeatur|contraeantur|escaeundus|escaeunde|escaeundos|escaeundorum|escaeundis|escaeunda|escaeundam|escaeundas|escaeundarum|escaeuntur|escaeatur|escaeantur|escaencia|escaenciam|escaencie|escaencias|escaenciarum|escaenciis|extraeundus|extraeunde|extraeundos|extraeundorum|extraeundis|extraeunda|extraeundam|extraeundas|extraeundarum|extraeuntur|extraeatur|extraeantur|aliaetos|aliaete|aliaeton|aliaeti|aliaeto|aliaetorum|aliaetis|aliaetus|aliaete|aliaetum|aliaeti|aliaeto|aliaetos|aliaetorum|aliaetis|tetraeterida|tetraeterin)$/i;

my $blocsOE = qr/^(?:adfoem|adfoemini|adfoemur|adfoemus|adfoent|adfoentur|adfoer|adfoeris|adfoes|adfoet|adfoetis|adfoetur|affoem|affoemini|affoemur|affoemus|affoent|affoentur|affoer|affoeris|affoes|affoet|affoetis|affoetur|aloe|aloem|aloen|aloeon|aloes|apoproegmena|apoproegmenis|apoproegmenorum|aporroea|aporroeam|aporroearum|aporroeas|aporroee|aporroeis|atizoe|atizoem|atizoen|atizoeon|atizoes|auoeria|auoeriam|auoeriarum|auoerias|auoerie|auoeriis|boe|boeci|boecie|boecii|boeciis|boecio|boeciorum|boecios|boecium|boecius|boem|boemini|boemur|boemus|boent|boentur|boer|boeris|boes|boet|boethe|boethi|boethis|boetho|boethorum|boethos|boethum|boethus|boeti|boetie|boetii|boetiis|boetio|boetiorum|boetios|boetis|boetium|boetius|boetur|boloe|boloem|boloen|boloeon|boloes|bradypoe|cacoethe|cacoethem|cacoethes|cacoethi|cacoethibus|cacoethis|cacoethium|caroena|caroeni|caroenis|caroeno|caroenorum|caroenum|centumboe|cloem|cloemini|cloemur|cloemus|cloent|cloentur|cloer|cloeris|cloes|cloet|cloetis|cloetur|coeam|coeamus|coeant|coeantur|coeas|coeat|coeatis|coeatur|coedifica|coedificabam|coedificabamini|coedificabamur|coedificabamus|coedificabant|coedificabantur|coedificabar|coedificabare|coedificabaris|coedificabas|coedificabat|coedificabatis|coedificabatur|coedificabere|coedificaberis|coedificabimini|coedificabimur|coedificabimus|coedificabis|coedificabit|coedificabitis|coedificabitur|coedificabo|coedificabor|coedificabunt|coedificabuntur|coedificacio|coedificacione|coedificacionem|coedificaciones|coedificacioni|coedificacionibus|coedificacionis|coedificacionum|coedificamini|coedificamur|coedificamus|coedificanda|coedificandam|coedificandarum|coedificandas|coedificande|coedificandi|coedificandis|coedificando|coedificandorum|coedificandos|coedificandum|coedificandus|coedificans|coedificant|coedificante|coedificantem|coedificantes|coedificanti|coedificantia|coedificantibus|coedificantis|coedificantium|coedificantur|coedificare|coedificarem|coedificaremini|coedificaremur|coedificaremus|coedificarent|coedificarentur|coedificarer|coedificarere|coedificareris|coedificares|coedificaret|coedificaretis|coedificaretur|coedificari|coedificaris|coedificas|coedificasse|coedificassem|coedificassemus|coedificassent|coedificasses|coedificasset|coedificassetis|coedificasti|coedificastis|coedificat|coedificata|coedificatam|coedificatarum|coedificatas|coedificate|coedificati|coedificatio|coedificatione|coedificationem|coedificationes|coedificationi|coedificationibus|coedificationis|coedificationum|coedificatis|coedificato|coedificatorum|coedificatos|coedificatote|coedificatu|coedificatum|coedificatur|coedificatura|coedificaturam|coedificaturarum|coedificaturas|coedificature|coedificaturi|coedificaturis|coedificaturo|coedificaturorum|coedificaturos|coedificaturum|coedificaturus|coedificatus|coedificaueram|coedificaueramus|coedificauerant|coedificaueras|coedificauerat|coedificaueratis|coedificauere|coedificauerim|coedificauerimus|coedificauerint|coedificaueris|coedificauerit|coedificaueritis|coedificauero|coedificauerunt|coedificaui|coedificauimus|coedificauisse|coedificauissem|coedificauissemus|coedificauissent|coedificauisses|coedificauisset|coedificauissetis|coedificauisti|coedificauistis|coedificauit|coedificem|coedificemini|coedificemur|coedificemus|coedificent|coedificentur|coedificer|coedificeris|coedifices|coedificet|coedificetis|coedificetur|coedifico|coedificor|coegeram|coegeramus|coegerant|coegeras|coegerat|coegeratis|coegere|coegerim|coegerimus|coegerint|coegeris|coegerit|coegeritis|coegero|coegerunt|coegi|coegimus|coegisse|coegissem|coegissemus|coegissent|coegisses|coegisset|coegissetis|coegisti|coegistis|coegit|coegrescam|coegrescamini|coegrescamur|coegrescamus|coegrescant|coegrescantur|coegrescar|coegrescare|coegrescaris|coegrescas|coegrescat|coegrescatis|coegrescatur|coegresce|coegrescebam|coegrescebamini|coegrescebamur|coegrescebamus|coegrescebant|coegrescebantur|coegrescebar|coegrescebare|coegrescebaris|coegrescebas|coegrescebat|coegrescebatis|coegrescebatur|coegrescemini|coegrescemur|coegrescemus|coegrescenda|coegrescendam|coegrescendarum|coegrescendas|coegrescende|coegrescendi|coegrescendis|coegrescendo|coegrescendorum|coegrescendos|coegrescendum|coegrescendus|coegrescens|coegrescent|coegrescente|coegrescentem|coegrescentes|coegrescenti|coegrescentia|coegrescentibus|coegrescentis|coegrescentium|coegrescentur|coegrescere|coegrescerem|coegresceremini|coegresceremur|coegresceremus|coegrescerent|coegrescerentur|coegrescerer|coegrescerere|coegrescereris|coegresceres|coegresceret|coegresceretis|coegresceretur|coegresceris|coegresces|coegrescet|coegrescete|coegrescetis|coegresceto|coegrescetote|coegrescetur|coegresci|coegrescimini|coegrescimur|coegrescimus|coegrescis|coegrescit|coegrescite|coegrescitis|coegrescito|coegrescitote|coegrescitur|coegresco|coegrescor|coegrescunt|coegrescuntur|coegrita|coegritam|coegritarum|coegritas|coegrite|coegriti|coegritis|coegrito|coegritorum|coegritos|coegritu|coegritum|coegritura|coegrituram|coegriturarum|coegrituras|coegriture|coegrituri|coegrituris|coegrituro|coegriturorum|coegrituros|coegriturum|coegriturus|coegritus|coegrota|coegrotabam|coegrotabamini|coegrotabamur|coegrotabamus|coegrotabant|coegrotabantur|coegrotabar|coegrotabare|coegrotabaris|coegrotabas|coegrotabat|coegrotabatis|coegrotabatur|coegrotabere|coegrotaberis|coegrotabimini|coegrotabimur|coegrotabimus|coegrotabis|coegrotabit|coegrotabitis|coegrotabitur|coegrotabo|coegrotabor|coegrotabunt|coegrotabuntur|coegrotamini|coegrotamur|coegrotamus|coegrotanda|coegrotandam|coegrotandarum|coegrotandas|coegrotande|coegrotandi|coegrotandis|coegrotando|coegrotandorum|coegrotandos|coegrotandum|coegrotandus|coegrotans|coegrotant|coegrotante|coegrotantem|coegrotantes|coegrotanti|coegrotantia|coegrotantibus|coegrotantis|coegrotantium|coegrotantur|coegrotare|coegrotarem|coegrotaremini|coegrotaremur|coegrotaremus|coegrotarent|coegrotarentur|coegrotarer|coegrotarere|coegrotareris|coegrotares|coegrotaret|coegrotaretis|coegrotaretur|coegrotari|coegrotaris|coegrotas|coegrotasse|coegrotassem|coegrotassemus|coegrotassent|coegrotasses|coegrotasset|coegrotassetis|coegrotasti|coegrotastis|coegrotat|coegrotata|coegrotatam|coegrotatarum|coegrotatas|coegrotate|coegrotati|coegrotatis|coegrotato|coegrotatorum|coegrotatos|coegrotatote|coegrotatu|coegrotatum|coegrotatur|coegrotatura|coegrotaturam|coegrotaturarum|coegrotaturas|coegrotature|coegrotaturi|coegrotaturis|coegrotaturo|coegrotaturorum|coegrotaturos|coegrotaturum|coegrotaturus|coegrotatus|coegrotaueram|coegrotaueramus|coegrotauerant|coegrotaueras|coegrotauerat|coegrotaueratis|coegrotauere|coegrotauerim|coegrotauerimus|coegrotauerint|coegrotaueris|coegrotauerit|coegrotaueritis|coegrotauero|coegrotauerunt|coegrotaui|coegrotauimus|coegrotauisse|coegrotauissem|coegrotauissemus|coegrotauissent|coegrotauisses|coegrotauisset|coegrotauissetis|coegrotauisti|coegrotauistis|coegrotauit|coegrotem|coegrotemini|coegrotemur|coegrotemus|coegrotent|coegrotentur|coegroter|coegroteris|coegrotes|coegrotet|coegrotetis|coegrotetur|coegroto|coegrotor|coegrueram|coegrueramus|coegruerant|coegrueras|coegruerat|coegrueratis|coegruere|coegruerim|coegruerimus|coegruerint|coegrueris|coegruerit|coegrueritis|coegruero|coegruerunt|coegrui|coegruimus|coegruisse|coegruissem|coegruissemus|coegruissent|coegruisses|coegruisset|coegruissetis|coegruisti|coegruistis|coegruit|coelecta|coelectam|coelectarum|coelectas|coelecte|coelecti|coelectior|coelectiora|coelectiore|coelectiorem|coelectiores|coelectiori|coelectioribus|coelectioris|coelectiorum|coelectis|coelectissima|coelectissimam|coelectissimarum|coelectissimas|coelectissime|coelectissimi|coelectissimis|coelectissimo|coelectissimorum|coelectissimos|coelectissimum|coelectissimus|coelectius|coelecto|coelectorum|coelectos|coelectum|coelectus|coelementata|coelementatam|coelementatarum|coelementatas|coelementate|coelementati|coelementatior|coelementatiora|coelementatiore|coelementatiorem|coelementatiores|coelementatiori|coelementatioribus|coelementatioris|coelementatiorum|coelementatis|coelementatissima|coelementatissimam|coelementatissimarum|coelementatissimas|coelementatissime|coelementatissimi|coelementatissimis|coelementatissimo|coelementatissimorum|coelementatissimos|coelementatissimum|coelementatissimus|coelementatius|coelementato|coelementatorum|coelementatos|coelementatum|coelementatus|coemam|coemamini|coemamur|coemamus|coemant|coemantur|coemar|coemare|coemaris|coemas|coemat|coematis|coematur|coeme|coemebam|coemebamini|coemebamur|coemebamus|coemebant|coemebantur|coemebar|coemebare|coemebaris|coemebas|coemebat|coemebatis|coemebatur|coememini|coememur|coememus|coemenda|coemendam|coemendarum|coemendas|coemendata|coemendatam|coemendatarum|coemendatas|coemendate|coemendati|coemendatior|coemendatiora|coemendatiore|coemendatiorem|coemendatiores|coemendatiori|coemendatioribus|coemendatioris|coemendatiorum|coemendatis|coemendatissima|coemendatissimam|coemendatissimarum|coemendatissimas|coemendatissime|coemendatissimi|coemendatissimis|coemendatissimo|coemendatissimorum|coemendatissimos|coemendatissimum|coemendatissimus|coemendatius|coemendato|coemendatorum|coemendatos|coemendatum|coemendatus|coemende|coemendi|coemendis|coemendo|coemendorum|coemendos|coemendum|coemendus|coemens|coement|coemente|coementem|coementes|coementi|coementia|coementibus|coementis|coementium|coementur|coemeram|coemeramus|coemerant|coemeras|coemerat|coemeratis|coemere|coemerem|coemeremini|coemeremur|coemeremus|coemerent|coemerentur|coemerer|coemerere|coemereris|coemeres|coemeret|coemeretis|coemeretur|coemerim|coemerimus|coemerint|coemeris|coemerit|coemeritis|coemero|coemerunt|coemes|coemet|coemete|coemetis|coemeto|coemetote|coemetur|coemi|coemimini|coemimur|coemimus|coemis|coemiseram|coemiseramus|coemiserant|coemiseras|coemiserat|coemiseratis|coemisere|coemiserim|coemiserimus|coemiserint|coemiseris|coemiserit|coemiseritis|coemisero|coemiserunt|coemisi|coemisimus|coemisisse|coemisissem|coemisissemus|coemisissent|coemisisses|coemisisset|coemisissetis|coemisisti|coemisistis|coemisit|coemissa|coemissam|coemissarum|coemissas|coemisse|coemissem|coemissemus|coemissent|coemisses|coemisset|coemissetis|coemissi|coemissis|coemisso|coemissorum|coemissos|coemissu|coemissum|coemissura|coemissuram|coemissurarum|coemissuras|coemissure|coemissuri|coemissuris|coemissuro|coemissurorum|coemissuros|coemissurum|coemissurus|coemissus|coemisti|coemistis|coemit|coemite|coemitis|coemito|coemitote|coemittam|coemittamini|coemittamur|coemittamus|coemittant|coemittantur|coemittar|coemittare|coemittaris|coemittas|coemittat|coemittatis|coemittatur|coemitte|coemittebam|coemittebamini|coemittebamur|coemittebamus|coemittebant|coemittebantur|coemittebar|coemittebare|coemittebaris|coemittebas|coemittebat|coemittebatis|coemittebatur|coemittemini|coemittemur|coemittemus|coemittenda|coemittendam|coemittendarum|coemittendas|coemittende|coemittendi|coemittendis|coemittendo|coemittendorum|coemittendos|coemittendum|coemittendus|coemittens|coemittent|coemittente|coemittentem|coemittentes|coemittenti|coemittentia|coemittentibus|coemittentis|coemittentium|coemittentur|coemittere|coemitterem|coemitteremini|coemitteremur|coemitteremus|coemitterent|coemitterentur|coemitterer|coemitterere|coemittereris|coemitteres|coemitteret|coemitteretis|coemitteretur|coemitteris|coemittes|coemittet|coemittete|coemittetis|coemitteto|coemittetote|coemittetur|coemitti|coemittimini|coemittimur|coemittimus|coemittis|coemittit|coemittite|coemittitis|coemittito|coemittitote|coemittitur|coemitto|coemittor|coemittunt|coemittuntur|coemitur|coemo|coemor|coempcio|coempcione|coempcionem|coempciones|coempcioni|coempcionibus|coempcionis|coempcionum|coempta|coemptam|coemptarum|coemptas|coempte|coempti|coemptio|coemptionale|coemptionalem|coemptionales|coemptionali|coemptionalia|coemptionalibus|coemptionalior|coemptionaliora|coemptionaliore|coemptionaliorem|coemptionaliores|coemptionaliori|coemptionalioribus|coemptionalioris|coemptionaliorum|coemptionalis|coemptionalissima|coemptionalissimam|coemptionalissimarum|coemptionalissimas|coemptionalissime|coemptionalissimi|coemptionalissimis|coemptionalissimo|coemptionalissimorum|coemptionalissimos|coemptionalissimum|coemptionalissimus|coemptionalium|coemptionalius|coemptionalum|coemptionator|coemptionatore|coemptionatorem|coemptionatores|coemptionatori|coemptionatoribus|coemptionatoris|coemptionatorum|coemptione|coemptionem|coemptiones|coemptioni|coemptionibus|coemptionis|coemptionum|coemptis|coempto|coemptor|coemptore|coemptorem|coemptores|coemptori|coemptoribus|coemptoris|coemptorum|coemptos|coemptu|coemptum|coemptura|coempturam|coempturarum|coempturas|coempture|coempturi|coempturis|coempturo|coempturorum|coempturos|coempturum|coempturus|coemptus|coemunt|coemuntur|coens|coente|coentem|coentes|coenti|coentia|coentibus|coentis|coentium|coeo|coeperam|coeperamus|coeperant|coeperas|coeperat|coeperatis|coepere|coeperim|coeperimus|coeperint|coeperis|coeperit|coeperitis|coepero|coeperunt|coepi|coepiam|coepiamini|coepiamur|coepiamus|coepiant|coepiantur|coepiar|coepiaris|coepias|coepiat|coepiatis|coepiatur|coepiebam|coepiebamini|coepiebamur|coepiebamus|coepiebant|coepiebantur|coepiebar|coepiebaris|coepiebas|coepiebat|coepiebatis|coepiebatur|coepiemini|coepiemur|coepiemus|coepienda|coepiendam|coepiendarum|coepiendas|coepiende|coepiendi|coepiendis|coepiendo|coepiendorum|coepiendos|coepiendum|coepiendus|coepiens|coepient|coepiente|coepientem|coepientes|coepienti|coepientia|coepientibus|coepientis|coepientium|coepientur|coepieram|coepieramus|coepierant|coepieras|coepierat|coepieratis|coepiere|coepierim|coepierimus|coepierint|coepieris|coepierit|coepieritis|coepiero|coepierunt|coepies|coepiet|coepietis|coepietur|coepii|coepiimus|coepiisse|coepiissem|coepiissemus|coepiissent|coepiisses|coepiisset|coepiissetis|coepiisti|coepiistis|coepiit|coepimini|coepimur|coepimus|coepio|coepior|coepire|coepirem|coepiremini|coepiremur|coepiremus|coepirent|coepirentur|coepirer|coepireris|coepires|coepiret|coepiretis|coepiretur|coepiri|coepiris|coepis|coepiscopatibus|coepiscopatu|coepiscopatui|coepiscopatum|coepiscopatus|coepiscopatuum|coepiscope|coepiscopi|coepiscopis|coepiscopo|coepiscoporum|coepiscopos|coepiscopum|coepiscopus|coepisse|coepissem|coepissemus|coepissent|coepisses|coepisset|coepissetis|coepisti|coepistis|coepit|coepita|coepitam|coepitarum|coepitas|coepite|coepiti|coepitis|coepito|coepitorum|coepitos|coepitote|coepitu|coepitum|coepitur|coepitura|coepituram|coepiturarum|coepituras|coepiture|coepituri|coepituris|coepituro|coepiturorum|coepituros|coepiturum|coepiturus|coepitus|coepiueram|coepiueramus|coepiuerant|coepiueras|coepiuerat|coepiueratis|coepiuere|coepiuerim|coepiuerimus|coepiuerint|coepiueris|coepiuerit|coepiueritis|coepiuero|coepiuerunt|coepiui|coepiuimus|coepiuisse|coepiuissem|coepiuissemus|coepiuissent|coepiuisses|coepiuisset|coepiuissetis|coepiuisti|coepiuistis|coepiuit|coepiunt|coepiuntur|coepta|coeptam|coeptarum|coeptas|coepte|coepti|coeptibus|coeptis|coepto|coeptorum|coeptos|coeptu|coeptui|coeptum|coeptura|coepturam|coepturarum|coepturas|coepture|coepturi|coepturis|coepturo|coepturorum|coepturos|coepturum|coepturus|coeptus|coeptuum|coepulabamini|coepulabamur|coepulabantur|coepulabar|coepulabare|coepulabaris|coepulabatur|coepulabere|coepulaberis|coepulabimini|coepulabimur|coepulabitur|coepulabor|coepulabuntur|coepulamini|coepulamur|coepulanda|coepulandam|coepulandarum|coepulandas|coepulande|coepulandi|coepulandis|coepulando|coepulandorum|coepulandos|coepulandum|coepulandus|coepulans|coepulante|coepulantem|coepulantes|coepulanti|coepulantia|coepulantibus|coepulantis|coepulantium|coepulantur|coepulare|coepularemini|coepularemur|coepularentur|coepularer|coepularere|coepulareris|coepularetur|coepulari|coepularis|coepulata|coepulatam|coepulatarum|coepulatas|coepulate|coepulati|coepulatis|coepulato|coepulatorum|coepulatos|coepulatum|coepulatur|coepulatura|coepulaturam|coepulaturarum|coepulaturas|coepulature|coepulaturi|coepulaturis|coepulaturo|coepulaturorum|coepulaturos|coepulaturum|coepulaturus|coepulatus|coepulemini|coepulemur|coepulentur|coepuler|coepulere|coepuleris|coepuletur|coepulone|coepuloni|coepulonis|coepulono|coepulonorum|coepulonos|coepulonum|coepulonus|coepulor|coequa|coequabam|coequabamini|coequabamur|coequabamus|coequabant|coequabantur|coequabar|coequabare|coequabaris|coequabas|coequabat|coequabatis|coequabatur|coequabere|coequaberis|coequabile|coequabilem|coequabiles|coequabili|coequabilia|coequabilibus|coequabilior|coequabiliora|coequabiliore|coequabiliorem|coequabiliores|coequabiliori|coequabilioribus|coequabilioris|coequabiliorum|coequabilis|coequabilissima|coequabilissimam|coequabilissimarum|coequabilissimas|coequabilissime|coequabilissimi|coequabilissimis|coequabilissimo|coequabilissimorum|coequabilissimos|coequabilissimum|coequabilissimus|coequabilium|coequabilius|coequabilum|coequabimini|coequabimur|coequabimus|coequabis|coequabit|coequabitis|coequabitur|coequabo|coequabor|coequabunt|coequabuntur|coequacio|coequacione|coequacionem|coequaciones|coequacioni|coequacionibus|coequacionis|coequacionum|coequale|coequalem|coequales|coequali|coequalia|coequalibus|coequalior|coequaliora|coequaliore|coequaliorem|coequaliores|coequaliori|coequalioribus|coequalioris|coequaliorum|coequalis|coequalissima|coequalissimam|coequalissimarum|coequalissimas|coequalissime|coequalissimi|coequalissimis|coequalissimo|coequalissimorum|coequalissimos|coequalissimum|coequalissimus|coequalitas|coequalitate|coequalitatem|coequalitates|coequalitati|coequalitatibus|coequalitatis|coequalitatum|coequaliter|coequalium|coequalius|coequalum|coequamini|coequamur|coequamus|coequanda|coequandam|coequandarum|coequandas|coequande|coequandi|coequandis|coequando|coequandorum|coequandos|coequandum|coequandus|coequans|coequant|coequante|coequantem|coequantes|coequanti|coequantia|coequantibus|coequantis|coequantium|coequantur|coequare|coequarem|coequaremini|coequaremur|coequaremus|coequarent|coequarentur|coequarer|coequarere|coequareris|coequares|coequaret|coequaretis|coequaretur|coequari|coequaris|coequas|coequasse|coequassem|coequassemus|coequassent|coequasses|coequasset|coequassetis|coequasti|coequastis|coequat|coequata|coequatam|coequatarum|coequatas|coequate|coequati|coequatio|coequatione|coequationem|coequationes|coequationi|coequationibus|coequationis|coequationum|coequatis|coequato|coequatorum|coequatos|coequatote|coequatu|coequatum|coequatur|coequatura|coequaturam|coequaturarum|coequaturas|coequature|coequaturi|coequaturis|coequaturo|coequaturorum|coequaturos|coequaturum|coequaturus|coequatus|coequaueram|coequaueramus|coequauerant|coequaueras|coequauerat|coequaueratis|coequauere|coequauerim|coequauerimus|coequauerint|coequaueris|coequauerit|coequaueritis|coequauero|coequauerunt|coequaui|coequauimus|coequauisse|coequauissem|coequauissemus|coequauissent|coequauisses|coequauisset|coequauissetis|coequauisti|coequauistis|coequauit|coequem|coequemini|coequemur|coequemus|coequent|coequentur|coequer|coequeris|coeques|coequet|coequetis|coequetur|coequo|coequor|coeram|coeramus|coerant|coeras|coerat|coeratis|coerccio|coerccione|coerccionem|coercciones|coerccioni|coerccionibus|coerccionis|coerccionum|coerce|coerceam|coerceamini|coerceamur|coerceamus|coerceant|coerceantur|coercear|coerceare|coercearis|coerceas|coerceat|coerceatis|coerceatur|coercebam|coercebamini|coercebamur|coercebamus|coercebant|coercebantur|coercebar|coercebare|coercebaris|coercebas|coercebat|coercebatis|coercebatur|coercebere|coerceberis|coercebimini|coercebimur|coercebimus|coercebis|coercebit|coercebitis|coercebitur|coercebo|coercebor|coercebunt|coercebuntur|coercemini|coercemur|coercemus|coercenda|coercendam|coercendarum|coercendas|coercende|coercendi|coercendis|coercendo|coercendorum|coercendos|coercendum|coercendus|coercens|coercent|coercente|coercentem|coercentes|coercenti|coercentia|coercentibus|coercentis|coercentium|coercentur|coerceo|coerceor|coercere|coercerem|coerceremini|coerceremur|coerceremus|coercerent|coercerentur|coercerer|coercerere|coercereris|coerceres|coerceret|coerceretis|coerceretur|coerceri|coerceris|coerces|coercet|coerceta|coercetam|coercetarum|coercetas|coercete|coerceti|coercetis|coerceto|coercetorum|coercetos|coercetote|coercetu|coercetum|coercetur|coercetura|coerceturam|coerceturarum|coerceturas|coerceture|coerceturi|coerceturis|coerceturo|coerceturorum|coerceturos|coerceturum|coerceturus|coercetus|coerceueram|coerceueramus|coerceuerant|coerceueras|coerceuerat|coerceueratis|coerceuere|coerceuerim|coerceuerimus|coerceuerint|coerceueris|coerceuerit|coerceueritis|coerceuero|coerceuerunt|coerceui|coerceuimus|coerceuisse|coerceuissem|coerceuissemus|coerceuissent|coerceuisses|coerceuisset|coerceuissetis|coerceuisti|coerceuistis|coerceuit|coercicio|coercicione|coercicionem|coerciciones|coercicioni|coercicionibus|coercicionis|coercicionum|coercio|coercione|coercionem|coerciones|coercioni|coercionibus|coercionis|coercionum|coercita|coercitacio|coercitacione|coercitacionem|coercitaciones|coercitacioni|coercitacionibus|coercitacionis|coercitacionum|coercitam|coercitarum|coercitas|coercitatio|coercitatione|coercitationem|coercitationes|coercitationi|coercitationibus|coercitationis|coercitationum|coercite|coerciti|coercitio|coercitione|coercitionem|coercitiones|coercitioni|coercitionibus|coercitionis|coercitionum|coercitis|coercito|coercitor|coercitore|coercitorem|coercitores|coercitori|coercitoribus|coercitoris|coercitorum|coercitos|coercitu|coercitum|coercitura|coercituram|coerciturarum|coercituras|coerciture|coercituri|coercituris|coercituro|coerciturorum|coercituros|coerciturum|coerciturus|coercitus|coerctio|coerctione|coerctionem|coerctiones|coerctioni|coerctionibus|coerctionis|coerctionum|coercueram|coercueramus|coercuerant|coercueras|coercuerat|coercueratis|coercuere|coercuerim|coercuerimus|coercuerint|coercueris|coercuerit|coercueritis|coercuero|coercuerunt|coercui|coercuimus|coercuisse|coercuissem|coercuissemus|coercuissent|coercuisses|coercuisset|coercuissetis|coercuisti|coercuistis|coercuit|coerimus|coeris|coerit|coeritis|coero|coerra|coerrabam|coerrabamini|coerrabamur|coerrabamus|coerrabant|coerrabantur|coerrabar|coerrabare|coerrabaris|coerrabas|coerrabat|coerrabatis|coerrabatur|coerrabere|coerraberis|coerrabimini|coerrabimur|coerrabimus|coerrabis|coerrabit|coerrabitis|coerrabitur|coerrabo|coerrabor|coerrabunt|coerrabuntur|coerramini|coerramur|coerramus|coerranda|coerrandam|coerrandarum|coerrandas|coerrande|coerrandi|coerrandis|coerrando|coerrandorum|coerrandos|coerrandum|coerrandus|coerrans|coerrant|coerrante|coerrantem|coerrantes|coerranti|coerrantia|coerrantibus|coerrantis|coerrantium|coerrantur|coerrare|coerrarem|coerraremini|coerraremur|coerraremus|coerrarent|coerrarentur|coerrarer|coerrarere|coerrareris|coerrares|coerraret|coerraretis|coerraretur|coerrari|coerraris|coerras|coerrasse|coerrassem|coerrassemus|coerrassent|coerrasses|coerrasset|coerrassetis|coerrasti|coerrastis|coerrat|coerrata|coerratam|coerratarum|coerratas|coerrate|coerrati|coerratica|coerraticam|coerraticarum|coerraticas|coerratice|coerratici|coerraticior|coerraticiora|coerraticiore|coerraticiorem|coerraticiores|coerraticiori|coerraticioribus|coerraticioris|coerraticiorum|coerraticis|coerraticissima|coerraticissimam|coerraticissimarum|coerraticissimas|coerraticissime|coerraticissimi|coerraticissimis|coerraticissimo|coerraticissimorum|coerraticissimos|coerraticissimum|coerraticissimus|coerraticius|coerratico|coerraticorum|coerraticos|coerraticum|coerraticus|coerratis|coerrato|coerratorum|coerratos|coerratote|coerratu|coerratum|coerratur|coerratura|coerraturam|coerraturarum|coerraturas|coerrature|coerraturi|coerraturis|coerraturo|coerraturorum|coerraturos|coerraturum|coerraturus|coerratus|coerraueram|coerraueramus|coerrauerant|coerraueras|coerrauerat|coerraueratis|coerrauere|coerrauerim|coerrauerimus|coerrauerint|coerraueris|coerrauerit|coerraueritis|coerrauero|coerrauerunt|coerraui|coerrauimus|coerrauisse|coerrauissem|coerrauissemus|coerrauissent|coerrauisses|coerrauisset|coerrauissetis|coerrauisti|coerrauistis|coerrauit|coerrem|coerremini|coerremur|coerremus|coerrent|coerrentur|coerrer|coerreris|coerres|coerret|coerretis|coerretur|coerro|coerror|coertio|coertione|coertionem|coertiones|coertioni|coertionibus|coertionis|coertionum|coerudi|coerudiam|coerudiamini|coerudiamur|coerudiamus|coerudiant|coerudiantur|coerudiar|coerudiare|coerudiaris|coerudias|coerudiat|coerudiatis|coerudiatur|coerudiebam|coerudiebamini|coerudiebamur|coerudiebamus|coerudiebant|coerudiebantur|coerudiebar|coerudiebare|coerudiebaris|coerudiebas|coerudiebat|coerudiebatis|coerudiebatur|coerudiemini|coerudiemur|coerudiemus|coerudienda|coerudiendam|coerudiendarum|coerudiendas|coerudiende|coerudiendi|coerudiendis|coerudiendo|coerudiendorum|coerudiendos|coerudiendum|coerudiendus|coerudiens|coerudient|coerudiente|coerudientem|coerudientes|coerudienti|coerudientia|coerudientibus|coerudientis|coerudientium|coerudientur|coerudieram|coerudieramus|coerudierant|coerudieras|coerudierat|coerudieratis|coerudiere|coerudierim|coerudierimus|coerudierint|coerudieris|coerudierit|coerudieritis|coerudiero|coerudierunt|coerudies|coerudiet|coerudietis|coerudietur|coerudii|coerudiimus|coerudiisse|coerudiissem|coerudiissemus|coerudiissent|coerudiisses|coerudiisset|coerudiissetis|coerudiisti|coerudiistis|coerudiit|coerudimini|coerudimur|coerudimus|coerudio|coerudior|coerudire|coerudirem|coerudiremini|coerudiremur|coerudiremus|coerudirent|coerudirentur|coerudirer|coerudirere|coerudireris|coerudires|coerudiret|coerudiretis|coerudiretur|coerudiri|coerudiris|coerudis|coerudit|coerudita|coeruditam|coeruditarum|coeruditas|coerudite|coeruditi|coeruditis|coerudito|coeruditorum|coeruditos|coeruditote|coeruditu|coeruditum|coeruditur|coeruditura|coerudituram|coeruditurarum|coerudituras|coeruditure|coerudituri|coerudituris|coerudituro|coeruditurorum|coerudituros|coeruditurum|coeruditurus|coeruditus|coerudiueram|coerudiueramus|coerudiuerant|coerudiueras|coerudiuerat|coerudiueratis|coerudiuere|coerudiuerim|coerudiuerimus|coerudiuerint|coerudiueris|coerudiuerit|coerudiueritis|coerudiuero|coerudiuerunt|coerudiui|coerudiuimus|coerudiuisse|coerudiuissem|coerudiuissemus|coerudiuissent|coerudiuisses|coerudiuisset|coerudiuissetis|coerudiuisti|coerudiuistis|coerudiuit|coerudiunt|coerudiuntur|coerunt|coes|coesse|coessem|coessemus|coessens|coessent|coessente|coessentem|coessentes|coessenti|coessentia|coessentiale|coessentialem|coessentiales|coessentiali|coessentialia|coessentialibus|coessentialior|coessentialiora|coessentialiore|coessentialiorem|coessentialiores|coessentialiori|coessentialioribus|coessentialioris|coessentialiorum|coessentialis|coessentialissima|coessentialissimam|coessentialissimarum|coessentialissimas|coessentialissime|coessentialissimi|coessentialissimis|coessentialissimo|coessentialissimorum|coessentialissimos|coessentialissimum|coessentialissimus|coessentialium|coessentialius|coessentialum|coessentibus|coessentior|coessentiora|coessentiore|coessentiorem|coessentiores|coessentiori|coessentioribus|coessentioris|coessentiorum|coessentis|coessentissima|coessentissimam|coessentissimarum|coessentissimas|coessentissime|coessentissimi|coessentissimis|coessentissimo|coessentissimorum|coessentissimos|coessentissimum|coessentissimus|coessentiua|coessentiuam|coessentiuarum|coessentiuas|coessentiue|coessentiui|coessentiuior|coessentiuiora|coessentiuiore|coessentiuiorem|coessentiuiores|coessentiuiori|coessentiuioribus|coessentiuioris|coessentiuiorum|coessentiuis|coessentiuissima|coessentiuissimam|coessentiuissimarum|coessentiuissimas|coessentiuissime|coessentiuissimi|coessentiuissimis|coessentiuissimo|coessentiuissimorum|coessentiuissimos|coessentiuissimum|coessentiuissimus|coessentiuius|coessentium|coessentiuo|coessentiuorum|coessentiuos|coessentius|coessentiuum|coessentiuus|coessentum|coesses|coesset|coessetis|coest|coeste|coestima|coestimabam|coestimabamini|coestimabamur|coestimabamus|coestimabant|coestimabantur|coestimabar|coestimabare|coestimabaris|coestimabas|coestimabat|coestimabatis|coestimabatur|coestimabere|coestimaberis|coestimabimini|coestimabimur|coestimabimus|coestimabis|coestimabit|coestimabitis|coestimabitur|coestimabo|coestimabor|coestimabunt|coestimabuntur|coestimamini|coestimamur|coestimamus|coestimanda|coestimandam|coestimandarum|coestimandas|coestimande|coestimandi|coestimandis|coestimando|coestimandorum|coestimandos|coestimandum|coestimandus|coestimans|coestimant|coestimante|coestimantem|coestimantes|coestimanti|coestimantia|coestimantibus|coestimantis|coestimantium|coestimantur|coestimare|coestimarem|coestimaremini|coestimaremur|coestimaremus|coestimarent|coestimarentur|coestimarer|coestimarere|coestimareris|coestimares|coestimaret|coestimaretis|coestimaretur|coestimari|coestimaris|coestimas|coestimasse|coestimassem|coestimassemus|coestimassent|coestimasses|coestimasset|coestimassetis|coestimasti|coestimastis|coestimat|coestimata|coestimatam|coestimatarum|coestimatas|coestimate|coestimati|coestimatis|coestimato|coestimatorum|coestimatos|coestimatote|coestimatu|coestimatum|coestimatur|coestimatura|coestimaturam|coestimaturarum|coestimaturas|coestimature|coestimaturi|coestimaturis|coestimaturo|coestimaturorum|coestimaturos|coestimaturum|coestimaturus|coestimatus|coestimaueram|coestimaueramus|coestimauerant|coestimaueras|coestimauerat|coestimaueratis|coestimauere|coestimauerim|coestimauerimus|coestimauerint|coestimaueris|coestimauerit|coestimaueritis|coestimauero|coestimauerunt|coestimaui|coestimauimus|coestimauisse|coestimauissem|coestimauissemus|coestimauissent|coestimauisses|coestimauisset|coestimauissetis|coestimauisti|coestimauistis|coestimauit|coestimem|coestimemini|coestimemur|coestimemus|coestiment|coestimentur|coestimer|coestimeris|coestimes|coestimet|coestimetis|coestimetur|coestimo|coestimor|coestis|coesto|coestote|coeta|coetabam|coetabamini|coetabamur|coetabamus|coetabant|coetabantur|coetabar|coetabare|coetabaris|coetabas|coetabat|coetabatis|coetabatur|coetabere|coetaberis|coetabimini|coetabimur|coetabimus|coetabis|coetabit|coetabitis|coetabitur|coetabo|coetabor|coetabunt|coetabuntur|coetamini|coetamur|coetamus|coetanda|coetandam|coetandarum|coetandas|coetande|coetandi|coetandis|coetando|coetandorum|coetandos|coetandum|coetandus|coetanea|coetaneabam|coetaneabamini|coetaneabamur|coetaneabamus|coetaneabant|coetaneabantur|coetaneabar|coetaneabare|coetaneabaris|coetaneabas|coetaneabat|coetaneabatis|coetaneabatur|coetaneabere|coetaneaberis|coetaneabimini|coetaneabimur|coetaneabimus|coetaneabis|coetaneabit|coetaneabitis|coetaneabitur|coetaneabo|coetaneabor|coetaneabunt|coetaneabuntur|coetaneam|coetaneamini|coetaneamur|coetaneamus|coetaneanda|coetaneandam|coetaneandarum|coetaneandas|coetaneande|coetaneandi|coetaneandis|coetaneando|coetaneandorum|coetaneandos|coetaneandum|coetaneandus|coetaneans|coetaneant|coetaneante|coetaneantem|coetaneantes|coetaneanti|coetaneantia|coetaneantibus|coetaneantis|coetaneantium|coetaneantur|coetaneare|coetanearem|coetanearemini|coetanearemur|coetanearemus|coetanearent|coetanearentur|coetanearer|coetanearere|coetaneareris|coetaneares|coetanearet|coetanearetis|coetanearetur|coetaneari|coetanearis|coetanearum|coetaneas|coetaneasse|coetaneassem|coetaneassemus|coetaneassent|coetaneasses|coetaneasset|coetaneassetis|coetaneasti|coetaneastis|coetaneat|coetaneata|coetaneatam|coetaneatarum|coetaneatas|coetaneate|coetaneati|coetaneatis|coetaneato|coetaneatorum|coetaneatos|coetaneatote|coetaneatu|coetaneatum|coetaneatur|coetaneatura|coetaneaturam|coetaneaturarum|coetaneaturas|coetaneature|coetaneaturi|coetaneaturis|coetaneaturo|coetaneaturorum|coetaneaturos|coetaneaturum|coetaneaturus|coetaneatus|coetaneaueram|coetaneaueramus|coetaneauerant|coetaneaueras|coetaneauerat|coetaneaueratis|coetaneauere|coetaneauerim|coetaneauerimus|coetaneauerint|coetaneaueris|coetaneauerit|coetaneaueritis|coetaneauero|coetaneauerunt|coetaneaui|coetaneauimus|coetaneauisse|coetaneauissem|coetaneauissemus|coetaneauissent|coetaneauisses|coetaneauisset|coetaneauissetis|coetaneauisti|coetaneauistis|coetaneauit|coetanee|coetaneem|coetaneemini|coetaneemur|coetaneemus|coetaneent|coetaneentur|coetaneer|coetaneeris|coetanees|coetaneet|coetaneetis|coetaneetur|coetanei|coetaneior|coetaneiora|coetaneiore|coetaneiorem|coetaneiores|coetaneiori|coetaneioribus|coetaneioris|coetaneiorum|coetaneis|coetaneissima|coetaneissimam|coetaneissimarum|coetaneissimas|coetaneissime|coetaneissimi|coetaneissimis|coetaneissimo|coetaneissimorum|coetaneissimos|coetaneissimum|coetaneissimus|coetaneius|coetaneo|coetaneor|coetaneorum|coetaneos|coetaneum|coetaneus|coetans|coetant|coetante|coetantem|coetantes|coetanti|coetantia|coetantibus|coetantis|coetantium|coetantur|coetare|coetarem|coetaremini|coetaremur|coetaremus|coetarent|coetarentur|coetarer|coetarere|coetareris|coetares|coetaret|coetaretis|coetaretur|coetari|coetaris|coetas|coetasse|coetassem|coetassemus|coetassent|coetasses|coetasset|coetassetis|coetasti|coetastis|coetat|coetata|coetatam|coetatarum|coetatas|coetate|coetati|coetatis|coetato|coetatorum|coetatos|coetatote|coetatu|coetatum|coetatur|coetatura|coetaturam|coetaturarum|coetaturas|coetature|coetaturi|coetaturis|coetaturo|coetaturorum|coetaturos|coetaturum|coetaturus|coetatus|coetaueram|coetaueramus|coetauerant|coetaueras|coetauerat|coetaueratis|coetauere|coetauerim|coetauerimus|coetauerint|coetaueris|coetauerit|coetaueritis|coetauero|coetauerunt|coetaui|coetauimus|coetauisse|coetauissem|coetauissemus|coetauissent|coetauisses|coetauisset|coetauissetis|coetauisti|coetauistis|coetauit|coetem|coetemini|coetemur|coetemus|coetent|coetentur|coeter|coeteris|coeterna|coeternale|coeternalem|coeternales|coeternali|coeternalia|coeternalibus|coeternalior|coeternaliora|coeternaliore|coeternaliorem|coeternaliores|coeternaliori|coeternalioribus|coeternalioris|coeternaliorum|coeternalis|coeternalissima|coeternalissimam|coeternalissimarum|coeternalissimas|coeternalissime|coeternalissimi|coeternalissimis|coeternalissimo|coeternalissimorum|coeternalissimos|coeternalissimum|coeternalissimus|coeternalitas|coeternalitate|coeternalitatem|coeternalitates|coeternalitati|coeternalitatibus|coeternalitatis|coeternalitatum|coeternalium|coeternalius|coeternalum|coeternam|coeternarum|coeternas|coeterne|coeterni|coeternior|coeterniora|coeterniore|coeterniorem|coeterniores|coeterniori|coeternioribus|coeternioris|coeterniorum|coeternis|coeternissima|coeternissimam|coeternissimarum|coeternissimas|coeternissime|coeternissimi|coeternissimis|coeternissimo|coeternissimorum|coeternissimos|coeternissimum|coeternissimus|coeternitas|coeternitate|coeternitatem|coeternitates|coeternitati|coeternitatibus|coeternitatis|coeternitatum|coeternius|coeterno|coeternorum|coeternos|coeternum|coeternus|coetes|coetet|coetetis|coetetur|coetibus|coeto|coetor|coetu|coetui|coetum|coetus|coetuum|coeua|coeuam|coeuangelista|coeuangelistam|coeuangelistarum|coeuangelistas|coeuangeliste|coeuangelistis|coeuarum|coeuas|coeue|coeuersio|coeuersione|coeuersionem|coeuersiones|coeuersioni|coeuersionibus|coeuersionis|coeuersionum|coeui|coeuior|coeuiora|coeuiore|coeuiorem|coeuiores|coeuiori|coeuioribus|coeuioris|coeuiorum|coeuis|coeuissima|coeuissimam|coeuissimarum|coeuissimas|coeuissime|coeuissimi|coeuissimis|coeuissimo|coeuissimorum|coeuissimos|coeuissimum|coeuissimus|coeuita|coeuitabam|coeuitabamini|coeuitabamur|coeuitabamus|coeuitabant|coeuitabantur|coeuitabar|coeuitabare|coeuitabaris|coeuitabas|coeuitabat|coeuitabatis|coeuitabatur|coeuitabere|coeuitaberis|coeuitabimini|coeuitabimur|coeuitabimus|coeuitabis|coeuitabit|coeuitabitis|coeuitabitur|coeuitabo|coeuitabor|coeuitabunt|coeuitabuntur|coeuitamini|coeuitamur|coeuitamus|coeuitanda|coeuitandam|coeuitandarum|coeuitandas|coeuitande|coeuitandi|coeuitandis|coeuitando|coeuitandorum|coeuitandos|coeuitandum|coeuitandus|coeuitans|coeuitant|coeuitante|coeuitantem|coeuitantes|coeuitanti|coeuitantia|coeuitantibus|coeuitantis|coeuitantium|coeuitantur|coeuitare|coeuitarem|coeuitaremini|coeuitaremur|coeuitaremus|coeuitarent|coeuitarentur|coeuitarer|coeuitarere|coeuitareris|coeuitares|coeuitaret|coeuitaretis|coeuitaretur|coeuitari|coeuitaris|coeuitas|coeuitasse|coeuitassem|coeuitassemus|coeuitassent|coeuitasses|coeuitasset|coeuitassetis|coeuitasti|coeuitastis|coeuitat|coeuitata|coeuitatam|coeuitatarum|coeuitatas|coeuitate|coeuitatem|coeuitates|coeuitati|coeuitatibus|coeuitatis|coeuitato|coeuitatorum|coeuitatos|coeuitatote|coeuitatu|coeuitatum|coeuitatur|coeuitatura|coeuitaturam|coeuitaturarum|coeuitaturas|coeuitature|coeuitaturi|coeuitaturis|coeuitaturo|coeuitaturorum|coeuitaturos|coeuitaturum|coeuitaturus|coeuitatus|coeuitaueram|coeuitaueramus|coeuitauerant|coeuitaueras|coeuitauerat|coeuitaueratis|coeuitauere|coeuitauerim|coeuitauerimus|coeuitauerint|coeuitaueris|coeuitauerit|coeuitaueritis|coeuitauero|coeuitauerunt|coeuitaui|coeuitauimus|coeuitauisse|coeuitauissem|coeuitauissemus|coeuitauissent|coeuitauisses|coeuitauisset|coeuitauissetis|coeuitauisti|coeuitauistis|coeuitauit|coeuitem|coeuitemini|coeuitemur|coeuitemus|coeuitent|coeuitentur|coeuiter|coeuiteris|coeuites|coeuitet|coeuitetis|coeuitetur|coeuito|coeuitor|coeuius|coeunda|coeundam|coeundarum|coeundas|coeunde|coeundi|coeundis|coeundo|coeundorum|coeundos|coeundum|coeundus|coeunt|coeunte|coeuntem|coeuntes|coeunti|coeuntia|coeuntibus|coeuntis|coeuntium|coeuntur|coeuo|coeuorum|coeuos|coeuum|coeuus|coex|coexcita|coexcitabam|coexcitabamini|coexcitabamur|coexcitabamus|coexcitabant|coexcitabantur|coexcitabar|coexcitabare|coexcitabaris|coexcitabas|coexcitabat|coexcitabatis|coexcitabatur|coexcitabere|coexcitaberis|coexcitabimini|coexcitabimur|coexcitabimus|coexcitabis|coexcitabit|coexcitabitis|coexcitabitur|coexcitabo|coexcitabor|coexcitabunt|coexcitabuntur|coexcitamini|coexcitamur|coexcitamus|coexcitanda|coexcitandam|coexcitandarum|coexcitandas|coexcitande|coexcitandi|coexcitandis|coexcitando|coexcitandorum|coexcitandos|coexcitandum|coexcitandus|coexcitans|coexcitant|coexcitante|coexcitantem|coexcitantes|coexcitanti|coexcitantia|coexcitantibus|coexcitantis|coexcitantium|coexcitantur|coexcitare|coexcitarem|coexcitaremini|coexcitaremur|coexcitaremus|coexcitarent|coexcitarentur|coexcitarer|coexcitarere|coexcitareris|coexcitares|coexcitaret|coexcitaretis|coexcitaretur|coexcitari|coexcitaris|coexcitas|coexcitasse|coexcitassem|coexcitassemus|coexcitassent|coexcitasses|coexcitasset|coexcitassetis|coexcitasti|coexcitastis|coexcitat|coexcitata|coexcitatam|coexcitatarum|coexcitatas|coexcitate|coexcitati|coexcitatis|coexcitato|coexcitatorum|coexcitatos|coexcitatote|coexcitatu|coexcitatum|coexcitatur|coexcitatura|coexcitaturam|coexcitaturarum|coexcitaturas|coexcitature|coexcitaturi|coexcitaturis|coexcitaturo|coexcitaturorum|coexcitaturos|coexcitaturum|coexcitaturus|coexcitatus|coexcitaueram|coexcitaueramus|coexcitauerant|coexcitaueras|coexcitauerat|coexcitaueratis|coexcitauere|coexcitauerim|coexcitauerimus|coexcitauerint|coexcitaueris|coexcitauerit|coexcitaueritis|coexcitauero|coexcitauerunt|coexcitaui|coexcitauimus|coexcitauisse|coexcitauissem|coexcitauissemus|coexcitauissent|coexcitauisses|coexcitauisset|coexcitauissetis|coexcitauisti|coexcitauistis|coexcitauit|coexcitem|coexcitemini|coexcitemur|coexcitemus|coexcitent|coexcitentur|coexciter|coexciteris|coexcites|coexcitet|coexcitetis|coexcitetur|coexcito|coexcitor|coexecutor|coexecutore|coexecutorem|coexecutores|coexecutori|coexecutoribus|coexecutoris|coexecutorum|coexistam|coexistamini|coexistamur|coexistamus|coexistant|coexistantur|coexistar|coexistare|coexistaris|coexistas|coexistat|coexistatis|coexistatur|coexiste|coexistebam|coexistebamini|coexistebamur|coexistebamus|coexistebant|coexistebantur|coexistebar|coexistebare|coexistebaris|coexistebas|coexistebat|coexistebatis|coexistebatur|coexistemini|coexistemur|coexistemus|coexistenda|coexistendam|coexistendarum|coexistendas|coexistende|coexistendi|coexistendis|coexistendo|coexistendorum|coexistendos|coexistendum|coexistendus|coexistens|coexistent|coexistente|coexistentem|coexistentes|coexistenti|coexistentia|coexistentibus|coexistentis|coexistentium|coexistentur|coexistere|coexisterem|coexisteremini|coexisteremur|coexisteremus|coexisterent|coexisterentur|coexisterer|coexisterere|coexistereris|coexisteres|coexisteret|coexisteretis|coexisteretur|coexisteris|coexistes|coexistet|coexistete|coexistetis|coexisteto|coexistetote|coexistetur|coexisti|coexistimini|coexistimur|coexistimus|coexistis|coexistit|coexistite|coexistitis|coexistito|coexistitote|coexistitur|coexisto|coexistor|coexistunt|coexistuntur|coexsistam|coexsistamini|coexsistamur|coexsistamus|coexsistant|coexsistantur|coexsistar|coexsistare|coexsistaris|coexsistas|coexsistat|coexsistatis|coexsistatur|coexsiste|coexsistebam|coexsistebamini|coexsistebamur|coexsistebamus|coexsistebant|coexsistebantur|coexsistebar|coexsistebare|coexsistebaris|coexsistebas|coexsistebat|coexsistebatis|coexsistebatur|coexsistemini|coexsistemur|coexsistemus|coexsistenda|coexsistendam|coexsistendarum|coexsistendas|coexsistende|coexsistendi|coexsistendis|coexsistendo|coexsistendorum|coexsistendos|coexsistendum|coexsistendus|coexsistens|coexsistent|coexsistente|coexsistentem|coexsistentes|coexsistenti|coexsistentia|coexsistentibus|coexsistentis|coexsistentium|coexsistentur|coexsistere|coexsisterem|coexsisteremini|coexsisteremur|coexsisteremus|coexsisterent|coexsisterentur|coexsisterer|coexsisterere|coexsistereris|coexsisteres|coexsisteret|coexsisteretis|coexsisteretur|coexsisteris|coexsistes|coexsistet|coexsistete|coexsistetis|coexsisteto|coexsistetote|coexsistetur|coexsisti|coexsistimini|coexsistimur|coexsistimus|coexsistis|coexsistit|coexsistite|coexsistiteram|coexsistiteramus|coexsistiterant|coexsistiteras|coexsistiterat|coexsistiteratis|coexsistitere|coexsistiterim|coexsistiterimus|coexsistiterint|coexsistiteris|coexsistiterit|coexsistiteritis|coexsistitero|coexsistiterunt|coexsistiti|coexsistitimus|coexsistitis|coexsistitisse|coexsistitissem|coexsistitissemus|coexsistitissent|coexsistitisses|coexsistitisset|coexsistitissetis|coexsistitisti|coexsistitistis|coexsistitit|coexsistito|coexsistitote|coexsistitur|coexsisto|coexsistor|coexsistunt|coexsistuntur|coexstincta|coexstinctam|coexstinctarum|coexstinctas|coexstincte|coexstincteram|coexstincteramus|coexstincterant|coexstincteras|coexstincterat|coexstincteratis|coexstinctere|coexstincterim|coexstincterimus|coexstincterint|coexstincteris|coexstincterit|coexstincteritis|coexstinctero|coexstincterunt|coexstincti|coexstinctimus|coexstinctior|coexstinctiora|coexstinctiore|coexstinctiorem|coexstinctiores|coexstinctiori|coexstinctioribus|coexstinctioris|coexstinctiorum|coexstinctis|coexstinctisse|coexstinctissem|coexstinctissemus|coexstinctissent|coexstinctisses|coexstinctisset|coexstinctissetis|coexstinctissima|coexstinctissimam|coexstinctissimarum|coexstinctissimas|coexstinctissime|coexstinctissimi|coexstinctissimis|coexstinctissimo|coexstinctissimorum|coexstinctissimos|coexstinctissimum|coexstinctissimus|coexstinctisti|coexstinctistis|coexstinctit|coexstinctius|coexstincto|coexstinctorum|coexstinctos|coexstinctu|coexstinctum|coexstinctura|coexstincturam|coexstincturarum|coexstincturas|coexstincture|coexstincturi|coexstincturis|coexstincturo|coexstincturorum|coexstincturos|coexstincturum|coexstincturus|coexstinctus|coexstinguam|coexstinguamini|coexstinguamur|coexstinguamus|coexstinguant|coexstinguantur|coexstinguar|coexstinguare|coexstinguaris|coexstinguas|coexstinguat|coexstinguatis|coexstinguatur|coexstingue|coexstinguebam|coexstinguebamini|coexstinguebamur|coexstinguebamus|coexstinguebant|coexstinguebantur|coexstinguebar|coexstinguebare|coexstinguebaris|coexstinguebas|coexstinguebat|coexstinguebatis|coexstinguebatur|coexstinguemini|coexstinguemur|coexstinguemus|coexstinguenda|coexstinguendam|coexstinguendarum|coexstinguendas|coexstinguende|coexstinguendi|coexstinguendis|coexstinguendo|coexstinguendorum|coexstinguendos|coexstinguendum|coexstinguendus|coexstinguens|coexstinguent|coexstinguente|coexstinguentem|coexstinguentes|coexstinguenti|coexstinguentia|coexstinguentibus|coexstinguentis|coexstinguentium|coexstinguentur|coexstinguere|coexstinguerem|coexstingueremini|coexstingueremur|coexstingueremus|coexstinguerent|coexstinguerentur|coexstinguerer|coexstinguerere|coexstinguereris|coexstingueres|coexstingueret|coexstingueretis|coexstingueretur|coexstingueris|coexstingues|coexstinguet|coexstinguete|coexstinguetis|coexstingueto|coexstinguetote|coexstinguetur|coexstingui|coexstinguimini|coexstinguimur|coexstinguimus|coexstinguis|coexstinguit|coexstinguite|coexstinguitis|coexstinguito|coexstinguitote|coexstinguitur|coexstinguo|coexstinguor|coexstinguunt|coexstinguuntur|coexstinxeram|coexstinxeramus|coexstinxerant|coexstinxeras|coexstinxerat|coexstinxeratis|coexstinxere|coexstinxerim|coexstinxerimus|coexstinxerint|coexstinxeris|coexstinxerit|coexstinxeritis|coexstinxero|coexstinxerunt|coexstinxi|coexstinximus|coexstinxisse|coexstinxissem|coexstinxissemus|coexstinxissent|coexstinxisses|coexstinxisset|coexstinxissetis|coexstinxisti|coexstinxistis|coexstinxit|coexstiteram|coexstiteramus|coexstiterant|coexstiteras|coexstiterat|coexstiteratis|coexstitere|coexstiterim|coexstiterimus|coexstiterint|coexstiteris|coexstiterit|coexstiteritis|coexstitero|coexstiterunt|coexstiti|coexstitimus|coexstitisse|coexstitissem|coexstitissemus|coexstitissent|coexstitisses|coexstitisset|coexstitissetis|coexstitisti|coexstitistis|coexstitit|coexsula|coexsulabam|coexsulabamini|coexsulabamur|coexsulabamus|coexsulabant|coexsulabantur|coexsulabar|coexsulabare|coexsulabaris|coexsulabas|coexsulabat|coexsulabatis|coexsulabatur|coexsulabere|coexsulaberis|coexsulabimini|coexsulabimur|coexsulabimus|coexsulabis|coexsulabit|coexsulabitis|coexsulabitur|coexsulabo|coexsulabor|coexsulabunt|coexsulabuntur|coexsulamini|coexsulamur|coexsulamus|coexsulanda|coexsulandam|coexsulandarum|coexsulandas|coexsulande|coexsulandi|coexsulandis|coexsulando|coexsulandorum|coexsulandos|coexsulandum|coexsulandus|coexsulans|coexsulant|coexsulante|coexsulantem|coexsulantes|coexsulanti|coexsulantia|coexsulantibus|coexsulantis|coexsulantium|coexsulantur|coexsulare|coexsularem|coexsularemini|coexsularemur|coexsularemus|coexsularent|coexsularentur|coexsularer|coexsularere|coexsulareris|coexsulares|coexsularet|coexsularetis|coexsularetur|coexsulari|coexsularis|coexsulas|coexsulasse|coexsulassem|coexsulassemus|coexsulassent|coexsulasses|coexsulasset|coexsulassetis|coexsulasti|coexsulastis|coexsulat|coexsulata|coexsulatam|coexsulatarum|coexsulatas|coexsulate|coexsulati|coexsulatis|coexsulato|coexsulatorum|coexsulatos|coexsulatote|coexsulatu|coexsulatum|coexsulatur|coexsulatura|coexsulaturam|coexsulaturarum|coexsulaturas|coexsulature|coexsulaturi|coexsulaturis|coexsulaturo|coexsulaturorum|coexsulaturos|coexsulaturum|coexsulaturus|coexsulatus|coexsulaueram|coexsulaueramus|coexsulauerant|coexsulaueras|coexsulauerat|coexsulaueratis|coexsulauere|coexsulauerim|coexsulauerimus|coexsulauerint|coexsulaueris|coexsulauerit|coexsulaueritis|coexsulauero|coexsulauerunt|coexsulaui|coexsulauimus|coexsulauisse|coexsulauissem|coexsulauissemus|coexsulauissent|coexsulauisses|coexsulauisset|coexsulauissetis|coexsulauisti|coexsulauistis|coexsulauit|coexsulem|coexsulemini|coexsulemur|coexsulemus|coexsulent|coexsulentur|coexsuler|coexsuleris|coexsules|coexsulet|coexsuletis|coexsuletur|coexsulo|coexsulor|coexsulta|coexsultabam|coexsultabamini|coexsultabamur|coexsultabamus|coexsultabant|coexsultabantur|coexsultabar|coexsultabare|coexsultabaris|coexsultabas|coexsultabat|coexsultabatis|coexsultabatur|coexsultabere|coexsultaberis|coexsultabimini|coexsultabimur|coexsultabimus|coexsultabis|coexsultabit|coexsultabitis|coexsultabitur|coexsultabo|coexsultabor|coexsultabunt|coexsultabuntur|coexsultamini|coexsultamur|coexsultamus|coexsultanda|coexsultandam|coexsultandarum|coexsultandas|coexsultande|coexsultandi|coexsultandis|coexsultando|coexsultandorum|coexsultandos|coexsultandum|coexsultandus|coexsultans|coexsultant|coexsultante|coexsultantem|coexsultantes|coexsultanti|coexsultantia|coexsultantibus|coexsultantis|coexsultantium|coexsultantur|coexsultare|coexsultarem|coexsultaremini|coexsultaremur|coexsultaremus|coexsultarent|coexsultarentur|coexsultarer|coexsultarere|coexsultareris|coexsultares|coexsultaret|coexsultaretis|coexsultaretur|coexsultari|coexsultaris|coexsultas|coexsultasse|coexsultassem|coexsultassemus|coexsultassent|coexsultasses|coexsultasset|coexsultassetis|coexsultasti|coexsultastis|coexsultat|coexsultata|coexsultatam|coexsultatarum|coexsultatas|coexsultate|coexsultati|coexsultatis|coexsultato|coexsultatorum|coexsultatos|coexsultatote|coexsultatu|coexsultatum|coexsultatur|coexsultatura|coexsultaturam|coexsultaturarum|coexsultaturas|coexsultature|coexsultaturi|coexsultaturis|coexsultaturo|coexsultaturorum|coexsultaturos|coexsultaturum|coexsultaturus|coexsultatus|coexsultaueram|coexsultaueramus|coexsultauerant|coexsultaueras|coexsultauerat|coexsultaueratis|coexsultauere|coexsultauerim|coexsultauerimus|coexsultauerint|coexsultaueris|coexsultauerit|coexsultaueritis|coexsultauero|coexsultauerunt|coexsultaui|coexsultauimus|coexsultauisse|coexsultauissem|coexsultauissemus|coexsultauissent|coexsultauisses|coexsultauisset|coexsultauissetis|coexsultauisti|coexsultauistis|coexsultauit|coexsultem|coexsultemini|coexsultemur|coexsultemus|coexsultent|coexsultentur|coexsulter|coexsulteris|coexsultes|coexsultet|coexsultetis|coexsultetur|coexsulto|coexsultor|coextendam|coextendamini|coextendamur|coextendamus|coextendant|coextendantur|coextendar|coextendare|coextendaris|coextendas|coextendat|coextendatis|coextendatur|coextende|coextendebam|coextendebamini|coextendebamur|coextendebamus|coextendebant|coextendebantur|coextendebar|coextendebare|coextendebaris|coextendebas|coextendebat|coextendebatis|coextendebatur|coextendemini|coextendemur|coextendemus|coextendenda|coextendendam|coextendendarum|coextendendas|coextendende|coextendendi|coextendendis|coextendendo|coextendendorum|coextendendos|coextendendum|coextendendus|coextendens|coextendent|coextendente|coextendentem|coextendentes|coextendenti|coextendentia|coextendentibus|coextendentis|coextendentium|coextendentur|coextenderam|coextenderamus|coextenderant|coextenderas|coextenderat|coextenderatis|coextendere|coextenderem|coextenderemini|coextenderemur|coextenderemus|coextenderent|coextenderentur|coextenderer|coextenderere|coextendereris|coextenderes|coextenderet|coextenderetis|coextenderetur|coextenderim|coextenderimus|coextenderint|coextenderis|coextenderit|coextenderitis|coextendero|coextenderunt|coextendes|coextendet|coextendete|coextendetis|coextendeto|coextendetote|coextendetur|coextendi|coextendimini|coextendimur|coextendimus|coextendis|coextendisse|coextendissem|coextendissemus|coextendissent|coextendisses|coextendisset|coextendissetis|coextendisti|coextendistis|coextendit|coextendite|coextenditis|coextendito|coextenditote|coextenditur|coextendo|coextendor|coextendunt|coextenduntur|coextensa|coextensam|coextensarum|coextensas|coextense|coextensi|coextensis|coextenso|coextensorum|coextensos|coextensu|coextensum|coextensura|coextensuram|coextensurarum|coextensuras|coextensure|coextensuri|coextensuris|coextensuro|coextensurorum|coextensuros|coextensurum|coextensurus|coextensus|coextenta|coextentam|coextentarum|coextentas|coextente|coextenti|coextentis|coextento|coextentorum|coextentos|coextentu|coextentum|coextentura|coextenturam|coextenturarum|coextenturas|coextenture|coextenturi|coextenturis|coextenturo|coextenturorum|coextenturos|coextenturum|coextenturus|coextentus|coextincta|coextinctam|coextinctarum|coextinctas|coextincte|coextincti|coextinctior|coextinctiora|coextinctiore|coextinctiorem|coextinctiores|coextinctiori|coextinctioribus|coextinctioris|coextinctiorum|coextinctis|coextinctissima|coextinctissimam|coextinctissimarum|coextinctissimas|coextinctissime|coextinctissimi|coextinctissimis|coextinctissimo|coextinctissimorum|coextinctissimos|coextinctissimum|coextinctissimus|coextinctius|coextincto|coextinctorum|coextinctos|coextinctum|coextinctus|coextinguam|coextinguamini|coextinguamur|coextinguamus|coextinguant|coextinguantur|coextinguar|coextinguare|coextinguaris|coextinguas|coextinguat|coextinguatis|coextinguatur|coextingue|coextinguebam|coextinguebamini|coextinguebamur|coextinguebamus|coextinguebant|coextinguebantur|coextinguebar|coextinguebare|coextinguebaris|coextinguebas|coextinguebat|coextinguebatis|coextinguebatur|coextinguemini|coextinguemur|coextinguemus|coextinguenda|coextinguendam|coextinguendarum|coextinguendas|coextinguende|coextinguendi|coextinguendis|coextinguendo|coextinguendorum|coextinguendos|coextinguendum|coextinguendus|coextinguens|coextinguent|coextinguente|coextinguentem|coextinguentes|coextinguenti|coextinguentia|coextinguentibus|coextinguentis|coextinguentium|coextinguentur|coextingueram|coextingueramus|coextinguerant|coextingueras|coextinguerat|coextingueratis|coextinguere|coextinguerem|coextingueremini|coextingueremur|coextingueremus|coextinguerent|coextinguerentur|coextinguerer|coextinguerere|coextinguereris|coextingueres|coextingueret|coextingueretis|coextingueretur|coextinguerim|coextinguerimus|coextinguerint|coextingueris|coextinguerit|coextingueritis|coextinguero|coextinguerunt|coextingues|coextinguet|coextinguete|coextinguetis|coextingueto|coextinguetote|coextinguetur|coextingui|coextinguimini|coextinguimur|coextinguimus|coextinguis|coextinguisse|coextinguissem|coextinguissemus|coextinguissent|coextinguisses|coextinguisset|coextinguissetis|coextinguisti|coextinguistis|coextinguit|coextinguite|coextinguitis|coextinguito|coextinguitote|coextinguitur|coextinguo|coextinguor|coextingustincta|coextingustinctam|coextingustinctarum|coextingustinctas|coextingustincte|coextingustincti|coextingustinctis|coextingustincto|coextingustinctorum|coextingustinctos|coextingustinctu|coextingustinctum|coextingustinctura|coextingustincturam|coextingustincturarum|coextingustincturas|coextingustincture|coextingustincturi|coextingustincturis|coextingustincturo|coextingustincturorum|coextingustincturos|coextingustincturum|coextingustincturus|coextingustinctus|coextinguunt|coextinguuntur|coexul|coexule|coexulem|coexules|coexuli|coexulibus|coexulis|coexulum|concoegeram|concoegeramus|concoegerant|concoegeras|concoegerat|concoegeratis|concoegere|concoegerim|concoegerimus|concoegerint|concoegeris|concoegerit|concoegeritis|concoegero|concoegerunt|concoegi|concoegimus|concoegisse|concoegissem|concoegissemus|concoegissent|concoegisses|concoegisset|concoegissetis|concoegisti|concoegistis|concoegit|coroeta|coroetam|coroetarum|coroetas|coroete|coroetis|croe|deaduoem|deaduoemini|deaduoemur|deaduoemus|deaduoent|deaduoentur|deaduoer|deaduoeris|deaduoes|deaduoet|deaduoetis|deaduoetur|doe|doeria|doerii|doeriis|doerio|doeriorum|doerium|edeatroe|enochoe|eoe|eopogdoe|epogdoe|eschoeta|eschoetam|eschoetarum|eschoetas|eschoete|eschoetis|euroe|excoeta|excoetam|excoetarum|excoetas|excoete|excoetis|foeda|foedi|foedis|foedo|foedorum|foedum|glasgoense|glasgoensem|glasgoenses|glasgoensi|glasgoensia|glasgoensibus|glasgoensis|glasgoensium|goecia|goeciam|goeciarum|goecias|goecie|goeciis|goetia|goetiam|goetiarum|goetias|goetie|goetiis|hermupoe|heroe|heroes|hoe|holoschoene|holoschoeni|holoschoenis|holoschoeno|holoschoenorum|holoschoenos|holoschoenum|holoschoenus|hydrochoe|hypoeolia|hypoeoliam|hypoeoliarum|hypoeolias|hypoeolie|hypoeolii|hypoeoliior|hypoeoliiora|hypoeoliiore|hypoeoliiorem|hypoeoliiores|hypoeoliiori|hypoeoliioribus|hypoeoliioris|hypoeoliiorum|hypoeoliis|hypoeoliissima|hypoeoliissimam|hypoeoliissimarum|hypoeoliissimas|hypoeoliissime|hypoeoliissimi|hypoeoliissimis|hypoeoliissimo|hypoeoliissimorum|hypoeoliissimos|hypoeoliissimum|hypoeoliissimus|hypoeoliius|hypoeolio|hypoeolior|hypoeoliora|hypoeoliore|hypoeoliorem|hypoeoliores|hypoeoliori|hypoeolioribus|hypoeolioris|hypoeoliorum|hypoeolios|hypoeolissima|hypoeolissimam|hypoeolissimarum|hypoeolissimas|hypoeolissime|hypoeolissimi|hypoeolissimis|hypoeolissimo|hypoeolissimorum|hypoeolissimos|hypoeolissimum|hypoeolissimus|hypoeolium|hypoeolius|inchoem|inchoemini|inchoemur|inchoemus|inchoent|inchoentur|inchoer|inchoeris|inchoes|inchoet|inchoetis|inchoetur|incoercita|incoercitam|incoercitarum|incoercitas|incoercite|incoerciti|incoercitior|incoercitiora|incoercitiore|incoercitiorem|incoercitiores|incoercitiori|incoercitioribus|incoercitioris|incoercitiorum|incoercitis|incoercitissima|incoercitissimam|incoercitissimarum|incoercitissimas|incoercitissime|incoercitissimi|incoercitissimis|incoercitissimo|incoercitissimorum|incoercitissimos|incoercitissimum|incoercitissimus|incoercitius|incoercito|incoercitorum|incoercitos|incoercitum|incoercitus|infoedacio|infoedacione|infoedacionem|infoedaciones|infoedacioni|infoedacionibus|infoedacionis|infoedacionum|infoedatio|infoedatione|infoedationem|infoedationes|infoedationi|infoedationibus|infoedationis|infoedationum|introeam|introeamus|introeant|introeantur|introeas|introeat|introeatis|introeatur|introeo|introeunda|introeundam|introeundarum|introeundas|introeunde|introeundi|introeundis|introeundo|introeundorum|introeundos|introeundum|introeundus|introeunt|introeunte|introeuntem|introeuntes|introeunti|introeuntia|introeuntibus|introeuntis|introeuntium|introeuntur|isoete|isoetem|isoetes|isoeti|isoetibus|isoetis|isoetium|loeria|loerii|loeriis|loerio|loeriorum|loerium|mansoeri|mansoerie|mansoerii|mansoeriis|mansoerio|mansoeriorum|mansoerios|mansoerium|mansoerius|masoeri|masoerie|masoerii|masoeriis|masoerio|masoeriorum|masoerios|masoerium|masoerius|mesauloe|moeta|moetam|moetarum|moetas|moete|moetis|myloece|myloeci|myloecis|myloeco|myloecon|myloecorum|myloecos|mythopoeia|mythopoeiam|mythopoeiarum|mythopoeias|mythopoeie|mythopoeii|mythopoeiior|mythopoeiiora|mythopoeiiore|mythopoeiiorem|mythopoeiiores|mythopoeiiori|mythopoeiioribus|mythopoeiioris|mythopoeiiorum|mythopoeiis|mythopoeiissima|mythopoeiissimam|mythopoeiissimarum|mythopoeiissimas|mythopoeiissime|mythopoeiissimi|mythopoeiissimis|mythopoeiissimo|mythopoeiissimorum|mythopoeiissimos|mythopoeiissimum|mythopoeiissimus|mythopoeiius|mythopoeio|mythopoeior|mythopoeiora|mythopoeiore|mythopoeiorem|mythopoeiores|mythopoeiori|mythopoeioribus|mythopoeioris|mythopoeiorum|mythopoeios|mythopoeissima|mythopoeissimam|mythopoeissimarum|mythopoeissimas|mythopoeissime|mythopoeissimi|mythopoeissimis|mythopoeissimo|mythopoeissimorum|mythopoeissimos|mythopoeissimum|mythopoeissimus|mythopoeium|mythopoeius|noe|noegea|noegei|noegeis|noegeo|noegeorum|noegeum|noemi|noera|noeram|noerarum|noeras|noere|noeri|noerior|noeriora|noeriore|noeriorem|noeriores|noeriori|noerioribus|noerioris|noeriorum|noeris|noerissima|noerissimam|noerissimarum|noerissimas|noerissime|noerissimi|noerissimis|noerissimo|noerissimorum|noerissimos|noerissimum|noerissimus|noerius|noero|noerorum|noeros|noerum|noerus|noeta|noete|noeti|noetis|noeto|noeton|noetorum|noetos|oe|oloschoene|oloschoeni|oloschoenis|oloschoeno|oloschoenorum|oloschoenos|oloschoenum|oloschoenus|paroecia|paroeciam|paroeciarum|paroecias|paroecie|paroeciis|paroetia|paroetiam|paroetiarum|paroetias|paroetie|paroetiis|patoencia|patoenciam|patoenciarum|patoencias|patoencie|patoenciis|patoentia|patoentiam|patoentiarum|patoentias|patoentie|patoentiis|poe|poema|poemacia|poemacii|poemaciis|poemacio|poemaciorum|poemacium|poemata|poemate|poemati|poematia|poematibus|poematii|poematiis|poematio|poematiorum|poematis|poematium|poematum|poese|poesem|poeseon|poeseos|poeses|poesi|poesibus|poesim|poesin|poesis|poesium|poesum|poeta|poetabam|poetabamini|poetabamur|poetabamus|poetabant|poetabantur|poetabar|poetabare|poetabaris|poetabas|poetabat|poetabatis|poetabatur|poetabere|poetaberis|poetabimini|poetabimur|poetabimus|poetabis|poetabit|poetabitis|poetabitur|poetabo|poetabor|poetabunt|poetabuntur|poetam|poetamini|poetamur|poetamus|poetanda|poetandam|poetandarum|poetandas|poetande|poetandi|poetandis|poetando|poetandorum|poetandos|poetandum|poetandus|poetans|poetant|poetante|poetantem|poetantes|poetanti|poetantia|poetantibus|poetantis|poetantium|poetantur|poetare|poetarem|poetaremini|poetaremur|poetaremus|poetarent|poetarentur|poetarer|poetarere|poetareris|poetares|poetaret|poetaretis|poetaretur|poetari|poetaris|poetarum|poetas|poetasse|poetassem|poetassemus|poetassent|poetasses|poetasset|poetassetis|poetasti|poetastis|poetat|poetata|poetatam|poetatarum|poetatas|poetate|poetati|poetatis|poetato|poetatorum|poetatos|poetatote|poetatu|poetatum|poetatur|poetatura|poetaturam|poetaturarum|poetaturas|poetature|poetaturi|poetaturis|poetaturo|poetaturorum|poetaturos|poetaturum|poetaturus|poetatus|poetaueram|poetaueramus|poetauerant|poetaueras|poetauerat|poetaueratis|poetauere|poetauerim|poetauerimus|poetauerint|poetaueris|poetauerit|poetaueritis|poetauero|poetauerunt|poetaui|poetauimus|poetauisse|poetauissem|poetauissemus|poetauissent|poetauisses|poetauisset|poetauissetis|poetauisti|poetauistis|poetauit|poete|poetem|poetemini|poetemur|poetemus|poetent|poetentur|poeter|poetere|poeteris|poetes|poetet|poetetis|poetetur|poetica|poeticam|poeticarum|poeticas|poetice|poeticem|poeticen|poeticeon|poetices|poetici|poeticior|poeticiora|poeticiore|poeticiorem|poeticiores|poeticiori|poeticioribus|poeticioris|poeticiorum|poeticis|poeticissima|poeticissimam|poeticissimarum|poeticissimas|poeticissime|poeticissimi|poeticissimis|poeticissimo|poeticissimorum|poeticissimos|poeticissimum|poeticissimus|poeticius|poetico|poeticorum|poeticos|poeticum|poeticus|poetis|poeto|poetor|poetri|poetria|poetriam|poetriarum|poetrias|poetrida|poetride|poetridem|poetrides|poetridi|poetridibus|poetridis|poetridum|poetrie|poetriis|poetrin|poetris|pomoeria|pomoerii|pomoeriis|pomoerio|pomoeriorum|pomoerium|proanennoeta|proanennoete|proanennoeti|proanennoetis|proanennoeto|proanennoeton|proanennoetorum|proanennoetos|proeconomia|proeconomiam|proeconomiarum|proeconomias|proeconomie|proeconomiis|proedificata|proedificati|proedificatis|proedificato|proedificatorum|proedificatum|proemptor|proemptore|proemptorem|proemptores|proemptori|proemptoribus|proemptoris|proemptorum|proexsili|proexsiliam|proexsiliamini|proexsiliamur|proexsiliamus|proexsiliant|proexsiliantur|proexsiliar|proexsiliare|proexsiliaris|proexsilias|proexsiliat|proexsiliatis|proexsiliatur|proexsiliebam|proexsiliebamini|proexsiliebamur|proexsiliebamus|proexsiliebant|proexsiliebantur|proexsiliebar|proexsiliebare|proexsiliebaris|proexsiliebas|proexsiliebat|proexsiliebatis|proexsiliebatur|proexsiliemini|proexsiliemur|proexsiliemus|proexsilienda|proexsiliendam|proexsiliendarum|proexsiliendas|proexsiliende|proexsiliendi|proexsiliendis|proexsiliendo|proexsiliendorum|proexsiliendos|proexsiliendum|proexsiliendus|proexsiliens|proexsilient|proexsiliente|proexsilientem|proexsilientes|proexsilienti|proexsilientia|proexsilientibus|proexsilientis|proexsilientium|proexsilientur|proexsiliere|proexsilieris|proexsilies|proexsiliet|proexsilietis|proexsilietur|proexsilimini|proexsilimur|proexsilimus|proexsilio|proexsilior|proexsilire|proexsilirem|proexsiliremini|proexsiliremur|proexsiliremus|proexsilirent|proexsilirentur|proexsilirer|proexsilirere|proexsilireris|proexsilires|proexsiliret|proexsiliretis|proexsiliretur|proexsiliri|proexsiliris|proexsilis|proexsilit|proexsilite|proexsilitis|proexsilito|proexsilitote|proexsilitur|proexsiliueram|proexsiliueramus|proexsiliuerant|proexsiliueras|proexsiliuerat|proexsiliueratis|proexsiliuere|proexsiliuerim|proexsiliuerimus|proexsiliuerint|proexsiliueris|proexsiliuerit|proexsiliueritis|proexsiliuero|proexsiliuerunt|proexsiliui|proexsiliuimus|proexsiliuisse|proexsiliuissem|proexsiliuissemus|proexsiliuissent|proexsiliuisses|proexsiliuisset|proexsiliuissetis|proexsiliuisti|proexsiliuistis|proexsiliuit|proexsiliunt|proexsiliuntur|proexsilueram|proexsilueramus|proexsiluerant|proexsilueras|proexsiluerat|proexsilueratis|proexsiluere|proexsiluerim|proexsiluerimus|proexsiluerint|proexsilueris|proexsiluerit|proexsilueritis|proexsiluero|proexsiluerunt|proexsilui|proexsiluimus|proexsiluisse|proexsiluissem|proexsiluissemus|proexsiluissent|proexsiluisses|proexsiluisset|proexsiluissetis|proexsiluisti|proexsiluistis|proexsiluit|proexsulta|proexsultam|proexsultarum|proexsultas|proexsulte|proexsulti|proexsultis|proexsulto|proexsultorum|proexsultos|proexsultu|proexsultum|proexsultura|proexsulturam|proexsulturarum|proexsulturas|proexsulture|proexsulturi|proexsulturis|proexsulturo|proexsulturorum|proexsulturos|proexsulturum|proexsulturus|proexsultus|protoeconome|protoeconomi|protoeconomis|protoeconomo|protoeconomorum|protoeconomos|protoeconomum|protoeconomus|pseudoecclesia|pseudoecclesiam|pseudoecclesiarum|pseudoecclesias|pseudoecclesie|pseudoecclesiis|pseudoepiscope|pseudoepiscopi|pseudoepiscopis|pseudoepiscopo|pseudoepiscoporum|pseudoepiscopos|pseudoepiscopum|pseudoepiscopus|pseudoeuangelista|pseudoeuangelistam|pseudoeuangelistarum|pseudoeuangelistas|pseudoeuangeliste|pseudoeuangelistis|psoea|psoeadica|psoeadicam|psoeadicarum|psoeadicas|psoeadice|psoeadicentior|psoeadicentiore|psoeadicentiorem|psoeadicentiores|psoeadicentiori|psoeadicentioribus|psoeadicentioris|psoeadicentiorum|psoeadicentissima|psoeadicentissimam|psoeadicentissimarum|psoeadicentissimas|psoeadicentissime|psoeadicentissimi|psoeadicentissimis|psoeadicentissimo|psoeadicentissimorum|psoeadicentissimos|psoeadicentissimum|psoeadicentissimus|psoeadici|psoeadiciora|psoeadiciore|psoeadiciori|psoeadicioribus|psoeadicioris|psoeadiciorum|psoeadicis|psoeadicius|psoeadico|psoeadicorum|psoeadicos|psoeadicum|psoeadicus|psoealgica|psoealgicam|psoealgicarum|psoealgicas|psoealgice|psoealgici|psoealgicior|psoealgiciora|psoealgiciore|psoealgiciorem|psoealgiciores|psoealgiciori|psoealgicioribus|psoealgicioris|psoealgiciorum|psoealgicis|psoealgicissima|psoealgicissimam|psoealgicissimarum|psoealgicissimas|psoealgicissime|psoealgicissimi|psoealgicissimis|psoealgicissimo|psoealgicissimorum|psoealgicissimos|psoealgicissimum|psoealgicissimus|psoealgicius|psoealgico|psoealgicorum|psoealgicos|psoealgicum|psoealgicus|psoeam|psoearum|psoeas|psoee|psoeis|reboem|reboemini|reboemur|reboemus|reboent|reboentur|reboer|reboeris|reboes|reboet|reboetis|reboetur|recoegeram|recoegeramus|recoegerant|recoegeras|recoegerat|recoegeratis|recoegere|recoegerim|recoegerimus|recoegerint|recoegeris|recoegerit|recoegeritis|recoegero|recoegerunt|recoegi|recoegimus|recoegisse|recoegissem|recoegissemus|recoegissent|recoegisses|recoegisset|recoegissetis|recoegisti|recoegistis|recoegit|retroeam|retroeamus|retroeant|retroeantur|retroeas|retroeat|retroeatis|retroeatur|retroeo|retroeunda|retroeundam|retroeundarum|retroeundas|retroeunde|retroeundi|retroeundis|retroeundo|retroeundorum|retroeundos|retroeundum|retroeundus|retroeunt|retroeunte|retroeuntem|retroeuntes|retroeunti|retroeuntia|retroeuntibus|retroeuntis|retroeuntium|retroeuntur|semipoeta|semipoetam|semipoetarum|semipoetas|semipoete|semipoetis|subintroeam|subintroeamus|subintroeant|subintroeantur|subintroeas|subintroeat|subintroeatis|subintroeatur|subintroeo|subintroeunda|subintroeundam|subintroeundarum|subintroeundas|subintroeunde|subintroeundi|subintroeundis|subintroeundo|subintroeundorum|subintroeundos|subintroeundum|subintroeundus|subintroeunt|subintroeunte|subintroeuntem|subintroeuntes|subintroeunti|subintroeuntia|subintroeuntibus|subintroeuntis|subintroeuntium|subintroeuntur|theopnoe|theopnoem|theopnoen|theopnoeon|theopnoes|trimoea|trimoeam|trimoearum|trimoeas|trimoee|trimoeis|ypoeolia|ypoeoliam|ypoeoliarum|ypoeolias|ypoeolie|ypoeolii|ypoeoliiora|ypoeoliiore|ypoeoliiori|ypoeoliioribus|ypoeoliioris|ypoeoliiorum|ypoeoliis|ypoeoliius|ypoeolio|ypoeolior|ypoeoliora|ypoeoliore|ypoeoliorem|ypoeoliores|ypoeoliori|ypoeolioribus|ypoeolioris|ypoeoliorum|ypoeolios|ypoeolissima|ypoeolissimam|ypoeolissimarum|ypoeolissimas|ypoeolissime|ypoeolissimi|ypoeolissimis|ypoeolissimo|ypoeolissimorum|ypoeolissimos|ypoeolissimum|ypoeolissimus|ypoeolium|ypoeolius|proemia|proemii|proemiis|proemio|proemiorum|proemium|proemiabamini|proemiabamur|proemiabantur|proemiabar|proemiabare|proemiabaris|proemiabatur|proemiabere|proemiaberis|proemiabimini|proemiabimur|proemiabitur|proemiabor|proemiabuntur|proemiamini|proemiamur|proemiancium|proemianda|proemiandam|proemiandarum|proemiandas|proemiande|proemiandi|proemiandis|proemiando|proemiandorum|proemiandos|proemiandum|proemiandus|proemians|proemiante|proemiantem|proemiantes|proemianti|proemiantia|proemiantibus|proemiantis|proemiantium|proemiantur|proemiare|proemiaremini|proemiaremur|proemiarentur|proemiarer|proemiarere|proemiareris|proemiaretur|proemiari|proemiaris|proemiata|proemiatam|proemiatarum|proemiatas|proemiate|proemiati|proemiatis|proemiato|proemiatorum|proemiatos|proemiatum|proemiatur|proemiatura|proemiaturam|proemiaturarum|proemiaturas|proemiature|proemiaturi|proemiaturis|proemiaturo|proemiaturorum|proemiaturos|proemiaturum|proemiaturus|proemiatus|proemiemini|proemiemur|proemientur|proemier|proemiere|proemieris|proemietur|proemior)$/i;

my $blocsQUE = qr/^(?:abrelinque|absque|abusque|adeque|adusque|alicuicumque|alicuiuscumque|aliquacumque|aliquamcumque|aliquarumcumque|aliquascumque|alique|aliquecumque|aliquemcumque|aliquibuscumque|aliquicumque|aliquocumque|aliquodcumque|aliquorumcumque|aliquoscumque|alteruterque|alteramutramque|alterarumutrarumque|alterasutrasque|alterautraque|altereutreque|alterisutrisque|alteriusutriusque|alteriutrique|alterorumutrorumque|alterosutrosque|alteroutroque|alterumutrumque|animeque|antique|aque|astriloque|atque|attorque|blandiloque|boniloque|breuiloque|buseque|cantiloque|ceruantesque|circumquaque|circumtorque|circumundique|cloque|coinque|collique|concoque|confidentiloque|conque|contorque|coque|croque|cuicumque|cuique|cuiuiscumque|cuiuscumque|cuiusque|cuiusuiscumque|cumcumque|cumque|cunque|decoque|deiloque|delinque|delique|denique|derelinque|detorque|discoque|distorque|doctiloque|donique|dulciloque|dulcioreloque|ecque|eque|equiloque|excoque|extorque|fallaciloque|falsiloque|fatiloque|flexiloque|fratresque|grandiloque|hirque|hroque|hucusque|ideoque|inaniloque|incoque|ineque|inique|inquantumcumque|inque|interutrasque|intorque|inusque|irque|itaque|largiloque|linque|lique|longinque|magniloque|maleloque|maliloque|mariscalque|marque|mendaciloque|multiloque|mutiloque|namque|neque|neutique|nuncusque|oblique|obliquiloque|obliquoloque|obtorque|odoriseque|ollicoque|olque|pediseque|pedisseque|perantique|percoque|pereque|perinique|perlonginque|perpropinque|pertorque|perubique|planiloque|pleramque|pleraque|plerarumque|plerasque|plereque|plerique|plerisque|pleroque|plerorumque|plerosque|plerumque|plerusque|precoque|pretorque|propinque|quacumque|qualecumque|qualemcumque|qualescumque|qualiacumque|qualibuscumque|qualicumque|qualiscumque|qualitercumque|qualiumcumque|qualumcumque|quamcumque|quamdiucumque|quamdiucunque|quammagnacumque|quammagnamcumque|quammagnarumcumque|quammagnascumque|quammagnecumque|quammagnicumque|quammagniscumque|quammagnocumque|quammagnorumcumque|quammagnoscumque|quammagnumcumque|quammagnuscumque|quamque|quamuiscumque|quandocumque|quandoque|quantaculacumque|quantaculamcumque|quantacularumcumque|quantaculascumque|quantaculecumque|quantaculicumque|quantaculiscumque|quantaculocumque|quantaculorumcumque|quantaculoscumque|quantaculumcumque|quantaculuscumque|quantacumque|quantamcumque|quantarumcumque|quantascumque|quantecumque|quanticumque|quantiscumque|quantocumque|quantorumcumque|quantoscumque|quantulacumque|quantulamcumque|quantularumcumque|quantulascumque|quantulecumque|quantulicumque|quantuliscumque|quantulocumque|quantulorumcumque|quantuloscumque|quantulumcumque|quantuluscumque|quantumcumque|quantuscumque|quaque|quarumcumque|quarumque|quarumuiscumque|quascumque|quasque|quasuiscumque|quauiscumque|que|quecumque|quemcumque|quemque|quemuiscumque|queque|queuiscumque|quibuscumque|quibusque|quibusuiscumque|quicumque|quidque|quinque|quique|quisque|quiuiscumque|quoadusque|quocumque|quodcumque|quoduiscumque|quomodocumque|quoque|quorumcumque|quorumque|quorumuiscumque|quoscumque|quosque|quosuiscumque|quotacumque|quotamcumque|quotamquamque|quotaquaque|quotaqueque|quotarumcumque|quotarumquarumque|quotascumque|quotasquasque|quotcumque|quotecuique|quotecumque|quotequeque|quoticuiusque|quoticumque|quotienscumque|quotiensque|quotiquique|quotiscumque|quotisquibusque|quotocuique|quotocumque|quotoquoque|quotorumcumque|quotorumquorumque|quotoscumque|quotosquosque|quotumcumque|quotumquemque|quotumquidque|quotuscumque|quotusquisque|quouiscumque|quousque|recoque|relinque|relique|reloque|retorque|roque|sanctiloque|seculiloque|sesque|silique|soliseque|soque|sortiloque|sterlinque|stultiloque|suauiloque|subcoque|subrelinque|subseque|subtililoque|subtorque|tardiloque|tasque|terriloque|torque|turpiloque|uaniloque|ubicumque|ubicunque|ubiquaque|ubique|uentriloque|ueriloque|uersiloque|uersutiloque|undecumque|undecunque|undique|undiseque|unuscuique|unuscuiusque|unusquamque|unusquaque|unusquarumque|unusquasque|unusquemque|unusqueque|unusquibusque|unusquidque|unusquique|unusquisque|unusquoque|unusquorumque|unusquosque|usque|usquequaque|utcumque|utcunque|utercumque|utercunque|uterque|utique|utquomque|utracumque|utracunque|utramcumque|utramcunque|utramque|utraque|utrarumcumque|utrarumcunque|utrarumque|utrascumque|utrascunque|utrasque|utrecumque|utrecunque|utreque|utricumque|utricunque|utrimque|utrinque|utrique|utriscumque|utriscunque|utrisque|utriuscumque|utriuscunque|utriusque|utrobique|utrocumque|utrocunque|utroque|utrorumcumque|utrorumcunque|utrorumque|utroscumque|utroscunque|utrosque|utrubique|utrumcumque|utrumcunque|utrumque|utrumubique|waltmarque|quocienscumque|quociensque|unumquemque|uniuscuiusque|unicuique|unoquoque|unaqueque|unamquamque|unaquaque|unumquidque|adtorque|cuicunque|cuiuscunque|quacunque|quamcunque|quarumcunque|quascunque|quecunque|quemcunque|quibuscunque|quicunque|quocunque|quodcunque|quorumcunque|quoscunque|quociescumque|quotiescumque|unumquodque|quotiesque|undequaque)$/i;

# La variable $poubelle contient la liste des abréviations pour lesquelles nous recollons
# le point au mot qui le précède, mais que nous ne souhaitons pas lemmatiser ; ces abréviations
# sont mises entre crochets dans le fichier tokenisé, pour que le tree-tagger les ignore.

my $poubelle = qr/^(resp|uers|seq|cod|etc|al|pag|bibl|ms|tom|cap|lib|libr|mss|epist|ep|om|seqq|codd|add|ibid|fol|col|leg|sec|uet|rec|homil|ed|cartul|thess|hebr|ephes|tim|tit|coloss|ezech|deut|apoc|exod|matth|psal|psalm|ioan|luc|rom|gen|genes|isa|prou|reg|act|eccli|eccle|ierem|ier|marc|petr|gal|cant|ps|sap|aug|zach|cass|chrys|greg|hil|iac|philipp?)\.$/i;

# La variable $garde contient la liste des abréviations pour lesquelles nous recollons
# le point au mot qui le précède, et que nous souhaitons lemmatiser.
# my $garde = qr/^(kal|card|presb|indict|sg|sig|sign|sext|[sb]+?)\.$/i;


# Le hash %decoupage contient une liste de mots collés en latin, et
# que nous découpons pour les lemmatiser.
my %decoupage = (
    # QUE
    'cumque' => "cum\nque",
    'sicque' => "sic\nque",

    # NE
    'putasne' => "putas\nne",
    'utrumne' => "utrum\nne",
    'estne' => "est\nne",
    'ergone' => "ergo\nne",
    'potestne' => "potest\nne",
    'nihilne' => "nihil\nne",
    'rectene' => "recte\nne",
    'iamne' => "iam\nne",
    'etiamne' => "etiam\nne",
    'numquamne' => "numquam\nne",
    'nunquamne' => "nunquam\nne",
    'parumne' => "parum\nne",
    'tantumne' => "tantum\nne",
    'adeone' => "adeo\nne",
    'uidesne' => "uides\nne",
    'satisne' => "satis\nne",
    'sitne' => "sit\nne",
    'anne' => "an\nne",
    'dicturusne' => "dicturus\nne",
    'poteritne' => "poterit\nne",
    'sanusne' => "sanus\nne",
    'saluusne' => "saluus\nne",
    'pacificusne' => "pacificus\nne",
    'tune' => "tu\nne",

    # VE
    'honorisue' => "honoris\nue",
    'aquarumue' => "aquarum\nue",
    'heredisue' => "heredis\nue",
    'tertioue' => "tertio\nue",
    'tercioue' => "tercio\nue",
    'quidue' => "quid\nue",
    'queue' => "que\nue",
    'quaeue' => "que\nue",
    'quoue' => "quo\nue",
    'cuiue' => "cui\nue",
    'cuiusue' => "cuius\nue",
    'minusue' => "minus\nue",
    'secularisue' => "secularis\nue",
    'seculariue' => "seculari\nue",
    'saecularisue' => "secularis\nue",
    'saeculariue' => "seculari\nue",
    'quibusue' => "quibus\nue",
    'quaue' => "qua\nue",
    'quiue' => "qui\nue",
    'quisue' => "quis\nue",
    'aliaue' => "alia\nue",
    'aliiue' => "alii\nue",
    'alioue' => "alio\nue",
    'aliisue' => "aliis\nue",
    'aliarumue' => "aliarum\nue",
    'aliorumue' => "aliorum\nue",
    'suasue' => "suas\nue",
    'qualiterue' => "qualiter\nue",
    'qualisue' => "qualis\nue",
    'qualiue' => "quali\nue",
    'eiusue' => "eius\nue",
    'suarumue' => "suarum\nue",
    'suorumue' => "suorum\nue",
    'niueiue' => "niuei\nue",
    'obscenisue' => "obscenis\nue",
    'triduumue' => "triduum\nue",

    # MOTS EN -CUM
    'mecum' => "me\ncum",
    'tecum' => "te\ncum",
    'secum' => "se\ncum",
    'nobiscum' => "nobis\ncum",
    'uobiscum' => "uobis\ncum",
    'quocum' => "quo\ncum",
    'quibuscum' => "quibus\ncum",

    # MOTS EN -METIPSE
    'memetipse' => "memet\nipse",
    'memetipsa' => "memet\nipsa",
    'memetipsum' => "memet\nipsum",
    'memetipsam' => "memet\nipsam",
    'memetipso' => "memet\nipso",
    'michimetipse' => "michimet\nipse",
    'mihimetipsi' => "mihimet\nipsi",
    'temetipse' => "temet\nipse",
    'temetipsa' => "temet\nipsa",
    'temetipsum' => "temet\nipsum",
    'temetipsam' => "temet\nipsam",
    'temetipso' => "temet\nipso",
    'tumetipse' => "tumet\nipse",
    'tibimetipsi' => "tibimet\nipsi",
    'semetipse' => "semet\nipse",
    'semetipsum' => "semet\nipsum",
    'semetipsa' => "semet\nipsa",
    'semetipsam' => "semet\nipsam",
    'semetipso' => "semet\nipso",
    'semetipsos' => "semet\nipsos",
    'semetipsas' => "semet\nipsas",
    'semetipsis' => "semet\nipsis",
    'sibimetipse' => "sibimet\nipse",
    'sibimetipsis' => "sibimet\nipsis",
    'sibimetipsi' => "sibimet\nipsi",
    'suimetipsius' => "suimet\nipsius",
    'nosmetipsos' => "nosmet\nipsos",
    'nosmetipsi' => "nosmet\nipsi",
    'nobismetipsis' => "nobismet\nipsis",
    'uosmetipsi' => "uosmet\nipsi",
    'uosmetipsos' => "uosmet\nipsos",
    'uosmetipsas' => "uosmet\nipsas",
    'uobismetipsis' => "uobismet\nipsis",

    # -ipse
    'meipsam' => "me\nipsam",
    'meipso' => "me\nipso",
    'meipsum' => "me\nipsum",
    'teipsum' => "te\nipsum",
    'teipsam' => "te\nipsam",
    'teipso' => "te\nipso",
    'seipse' => "se\nipse",
    'seipsa' => "se\nipsa",
    'seipsum' => "se\nipsum",
    'seipsam' => "se\nipsam",
    'seipsos' => "se\nipsos",
    'seipso' => "se\nipso",
    'sibiipsi' => "sibi\nipsi",
    'suiipsius' => "sui\nipsius",
    'idipsum' => "id\nipsum",
    'nobisipsi' => "nobis\nipsi",
    'nobisipsis' => "nobis\nipsis",
    'nosipsi' => "nos\nipsi",
    'nosipsos' => "nos\nipsos",
    'uosipsos' => "uos\nipsos",
    'uobisipsi' => "uobis\nipsi",
    'uobisipsis' => "uobis\nipsis",
    'uosipsi' => "uos\nipsi",
    'seipsi' => "se\nipsi",
    'seipsas' => "se\nipsas",
    'seipsis' => "se\nipsis",
    'sibiipsis' => "sibi\nipsis",

    # - TENUS
    'aliatenus' => "alia\ntenus",
    'aliotenus' => "alio\ntenus",
    'auretenus' => "aure\ntenus",
    'calcetenus' => "calce\ntenus",
    'capulotenus' => "capulo\ntenus",
    'celotenus' => "celo\ntenus",
    'ceruicetenus' => "ceruice\ntenus",
    'cingulotenus' => "cingulo\ntenus",
    'collotenus' => "collo\ntenus",
    'cordetenus' => "corde\ntenus",
    'cumulotenus' => "cumulo\ntenus",
    'facietenus' => "facie\ntenus",
    'fidetenus' => "fide\ntenus",
    'finetenus' => "fine\ntenus",
    'fundotenus' => "fundo\ntenus",
    'genutenus' => "genu\ntenus",
    'gulatenus' => "gula\ntenus",
    'humerotenus' => "humero\ntenus",
    'humotenus' => "humo\ntenus",
    'lectotenus' => "lecto\ntenus",
    'lethotenus' => "letho\ntenus",
    'medulletenus' => "medulle\ntenus",
    'mortetenus' => "morte\ntenus",
    'mosellatenus' => "mosella\ntenus",
    'murotenus' => "muro\ntenus",
    'nominetenus' => "nomine\ntenus",
    'oretenus' => "ore\ntenus",
    'pedetenus' => "pede\ntenus",
    'pubetenus' => "pube\ntenus",
    'puppetenus' => "puppe\ntenus",
    'rhenotenus' => "rheno\ntenus",
    'sacramentotenus' => "sacramento\ntenus",
    'solotenus' => "solo\ntenus",
    'specietenus' => "specie\ntenus",
    'summatenus' => "summa\ntenus",
    'summotenus' => "summo\ntenus",
    'superficietenus' => "superficie\ntenus",
    'terratenus' => "terra\ntenus",
    'uerbotenus' => "uerbo\ntenus",
    'uitatenus' => "uita\ntenus",
    'umbilicotenus' => "umbilico\ntenus",
    'unguetenus' => "ungue\ntenus",
    'zeugmatenus' => "zeugma\ntenus",

    # NOMBRES
    # Composés de decimus et sesqui- (je ne peux pas faire
    # d'expression régulière ici, je prends donc la liste
    # de ce que je trouve attesté)
    'decimatertia' => "decima\ntertia",
    'decimitertii' => "decimi\ntertii",
    'decimotertio' => "decimo\ntertio",
    'decimumtertium' => "decimum\ntertium",
    'decimaquarta' => "decima\nquarta",
    'decimiquarti' => "decimi\nquarti",
    'decimumquartum' => "decimum\nquartum",
    'decimusquartus' => "decimus\nquartus",
    'decimaquartam' => "decima\nquartam",
    'decimoquarto' => "decimo\nquarto",
    'decimamquintam' => "decimam\nquintam",
    'decimaquinta' => "decima\nquinta",
    'decimoquinto' => "decimo\nquinto",
    'decimumquintum' => "decimum\nquintum",
    'decimasexta' => "decima\nsexta",
    'decimisexti' => "decimi\nsexti",
    'decimosexto' => "decimo\nsexto",
    'decimumsextum' => "decimum\nsextum",
    'decimaseptima' => "decima\nseptima",
    'decimoseptimo' => "decimo\nseptimo",
    'decimumseptimum' => "decimum\nseptimum",
    'decimusseptimus' => "decimus\nseptimus",
    'decimiseptimi' => "decimi\nseptimi",
    'decimaoctaua' => "decima\noctaua",
    'decimoctauo' => "decim\noctauo",
    'decimumoctauum' => "decimum\noctauum",
    'decimusoctauus' => "decimus\noctauus",
    'decimioctaui' => "decimi\noctaui",
    'decimooctauo' => "decimo\noctauo",
    'decimanona' => "decima\nnona",
    'decimonono' => "decimo\nnono",
    'decimumnonum' => "decimum\nnonum",
    'decimusnonus' => "decimus\nnonus",
    'decimenone' => "decime\nnone",
    'sesquioctauae' => "sesqui\noctaue",
    'sesquioctaue' => "sesqui\noctaue",
    'sesquioctaui' => "sesqui\noctaui",
    'sesquioctauos' => "sesqui\noctauos",
    'sesquioctaua' => "sesqui\noctaua",
    'sesquioctauam' => "sesqui\noctauam",
    'sesquioctauis' => "sesqui\noctauis",
    'sesquioctauum' => "sesqui\noctauum",
    'sesquioctauadecima' => "sesqui\noctaua\ndecima",
    'sesquioctauas' => "sesqui\noctauas",
    'sesquioctauo' => "sesqui\noctauo",
    'sesquioctauus' => "sesqui\noctauus",
    # Autres
    'uigintiquatuor' => "uiginti\nquatuor",
    'uigintiquattuor' => "uiginti\nquattuor",

    # DIVERS
    'aliquomodo' => "aliquo\nmodo",
    'nullomodo' => "nullo\nmodo",
    'proculdubio' => "procul\ndubio",
    'uerumetiam' => "uerum\netiam",
    'inposterum' => "in\nposterum",
    'imposterum' => "in\nposterum",
    'inintegrum' => "in\nintegrum",
    'abintegrum' => "ab\nintegrum",
    'idest' => "id\nest",
    'posthec' => "post\nhec",
    'posthaec' => "post\nhec",
    'siquis' => "si\nquis",
    'siqua' => "si\nqua",
    'nequando' => "ne\nquando",
    'usquequo' => "usque\nquo",
    'usquedum' => "usque\ndum",
    'sepenumero' => "sepe\nnumero",
    'saepenumero' => "sepe\nnumero",
    'spicanardi' => "spica\nnardi",
    );


# Le hash %resolutions transforme certaines abréviations
my %resolution = (
    'bte' => 'beate',
    'btum' => 'beatum',
    'bti' => 'beati',
    'bto' => 'beato',
    'ste' => 'sancte',
    'stum' => 'sanctum',
    'sti' => 'sancti',
    # 'sto' => 'sancto', # commenté, à cause de sto, stare
    );


# Le hash %memoriser garde en mémoire la façon dont les mots ont été traités ;
# dès leur deuxième passage, ils n'ont plus à passer dans la boucle mais sont
# traités immédiatement.

my %memoriser;

foreach my $fic1 (@ARGV) {

    # Pour le cas où on voudrait utiliser le tokeniseur au sein d'un autre programme,
    # il faut veiller à mettre le préfixe au bon endroit du nom de fichier.
    my ($fichier,$chemin) = fileparse($fic1);
    my $fic2 = $chemin . "token_${fichier}";

    # Ouverture du fichier source
    open (MONTEXTE, "<$fic1") or die("Impossible d'ouvrir $fic1\n");

    # Création d'un fichier cible
    open (MONTEXTE2, ">$fic2") or die("Impossible d'ouvrir $fic2\n");

    # Affectation du texte à une variable scalaire
    undef $/;
    my $T = <MONTEXTE>;

    # Affichage de la progression :
    # le nom du fichier s'affiche dans le terminal
    print STDERR "$fic1\n";

    ###################
    # MODIFICATIONS : #
    ###################

    # Remplacement des J et V
    $T =~ tr/JVjv/IUiu/ ;

    # Traitement des diphtongues
    $T =~ s/æ/ae/g ;
    $T =~ s/œ/oe/g ;
    $T =~ s/Æ/Ae/g ;
    $T =~ s/Œ/Oe/g ;

    # Transformation des voyelles accentuées
    $T =~ tr/éèêëęȩàâáäîìíïòóöôùûúü/eeeeeeaaaaiiiioooouuuu/ ;

    # Suppression des caractères non souhaités
    $T =~ s@[^0-9A-Za-z;,:!\.\?"\(\)\[\]\ <>/=]@ @g ;

    # Insertion d'une espace avant et après les signes de ponctuation
    $T =~ s/([\.;,:!\?"\(\)\[\]])/ $1 /g ;

    # Élimination de signes de ponctuation successifs
    $T =~ s/ ([\.;,:!\?"\(\)\[\]]) (?:[\.;,:!\?"\(\)\[\]]) / $1 /g ;

    # ### Traitement propre aux balises :
    # # - une espace de chaque côté de la balise
    # $T =~ s@(<[^<]+?>)@ $1 @g ;
    # # - remplacement des espaces dans la balise par des underscores
    # 1 while $T =~ s@(<[^<]*?) ([^<]*?>)@$1_$2@g ;
    # # traitement des slashs hors balises
    # $T =~ s@([^<])(/)([^>])@$1 <$2> $3@g ;

    # Traitement des espaces avant les points
    $T =~ s/\s+/ /g ;
    $T =~ s/\s\./\./g ;
    $T =~ s/\.+/\./g ;

    # Le fichier est converti en liste, dont
    # chaque mot est un élément
    my @mots = split(/ /, $T);

    # Quand un mot est entièrement en majuscules,
    # on ne conserve que la majuscule initiale
    map { $_ = ucfirst(lc($_)) if $_ =~ m@[A-Z][A-Z]@;} @mots;

    # Fin du traitement global ; à partir de là, on traite chaque mot
    # séparément.
    foreach my $m (@mots) {

	my $point = '';

	# D'abord le traitement des points :
	if ($m =~ m@\.$@) {
	    # Si c'est une abréviation qu'on ne veut pas lemmatiser
	    if ($m =~ m@$poubelle@) {
		# on la met entre balises
	    	$m = '<' . $m . '>';
	    }
	    # Si c'est une abréviation qu'on garde... # commenté
	    # elsif ($m =~ m@$garde@) {
	    # 	# ... rien à faire
	    # }
	    # Si c'est un mot normal avec un point à la fin,
	    # on retire le point, qu'on stocke dans la variable $point,
	    # et on continue.
	    else {
		$point = chop($m);
	    }
	}

	# On mémorise le mot avant son traitement
	my $copie = $m;

	# On enregistre la valeur de bas-de-casse
	my $bdc = lc($m);

	# Si le mot a déjà été traité
	if (defined($memoriser{$copie})) {
	    $m = $memoriser{$copie}; # On lui donne d'emblée sa valeur finale
	}
	# Si le mot n'est pas susceptible d'être traité ensuite,
	# i.e. s'il est une ponctuation, une balise, ou n'a ni -ae-, ni -oe-, ni -que,
	# ni découpe, alors on n'y touche pas et on passe directement
	# à l'enregistrement
	elsif ($m =~ m@[?!:«»"-,;'()\[\]<]@ ||
	    ($m !~ m@[AaOo]e@ && $m !~ m@que$@ &&
	    $m !~ m@ue$@ && $m !~ m@ne$@ &&
	    $m !~ m@\d@ && !defined($decoupage{$bdc})
	    && !defined($resolution{$bdc}))
	    ) {
	    # Rien à faire dans la boucle, juste passer
	}

	# Sinon, c'est qu'il doit subir un traitement particulier :

	# -chiffres et nombres arabes
    	elsif ($m =~ m/\d+/){
	    $m = '<' . $m . '>';
	}
    	# Mots à découper
    	elsif (defined($decoupage{$bdc})) {
	    # Si le mot est en bdc :
	    if ($m =~ m@^[a-z]@) {
		$m = $decoupage{$bdc};
	    }
	    else {
		$m = ucfirst($decoupage{$bdc});
	    }
	}
    	# Abréviations à résoudre
    	elsif (defined($resolution{$bdc})) {
	    # Si le mot est en bdc :
	    if ($m =~ m@^[a-z]@) {
		$m = $resolution{$bdc};
	    }
	    else {
		$m = ucfirst($resolution{$bdc});
	    }
	}
	# diphtongues et -que final
    	else {
    	    ####################################
    	    # traitement des diphtongues ae oe #
    	    ####################################


	    # S'il y a la séquence 'ae' dans le mot :
    	    if ($bdc =~ m/ae/) {

    		# Liste de /ae/ à conserver :
    		if ($m =~ m@^(is[rm]ael|abimael|asael|asrael|azael|hazael|jathanael|jebnael|jephthael|jezrael|lael|mathusael|maviael|michael|misael|nathanael|phedael|raphael|subael|noemi)(.*?)$@i) {
    		    my ($debut,$fin) = ($1,$2);
    		    $fin =~ s@ae@e@g if $fin ne '';
    		    $m = $debut . $fin;
    		}
    		else {
    		    # Si le mot ne figure pas dans la liste AE
    		    if ($m !~ m@$blocsAE@) {
    			# RA : ajout du /g final pour traiter les mots à ae multiples (laetitiae) et du /i final pour, p. ex., aegypt-
    			$m =~ s/ae/e/ig ;
    		    }
    		}
    	    }

    	    if ($bdc =~ m/oe/) {
    		# Si le mot ne figure pas dans la liste OE
    		if ($m !~ m@$blocsOE@) {
    		    $m =~ s/oe/e/ig ;
    		}
    	    }

    	    ############################
    	    # traitement du -que final #
    	    ############################

    	    # S'il n'y a pas de -que final ...
    	    if ($m !~ m@que$@ || $m eq 'que') {
		# ... on peut passer immédiatement à la suite
	    }
    	    else {
    		# si un -que en finale,
    		# (1) on teste s'il se termine en cunque (pas -cumque : ambig. avec ducumque, p. ex.)
    		# (2) on teste l'appartenance à la liste à ne pas découper,
		# si présent, on enregistre et on passe à la suite
    		if ($m =~ m/unque$/) {
		    # Rien à faire
		}
		elsif ($m =~ m@$blocsQUE@) {
		    # Rien à faire
    		}
    		else {
		    # sinon, (3) on retire les trois dernières lettres et on fait 2 enregistrements distincts
		    chop($m); chop($m); chop($m);
		    $m = $m . "\n" . "que"; # pas de tiret dans les lemmes, tiret supprimé 20120201
    		}
    	    }
    	}

	# On remet la majuscule initiale à ceux qui pourraient
	# l'avoir perdue en route
	if ($copie =~ m@^[A-Z]@) {
	    $m = ucfirst($m);
	}

	$memoriser{$copie} = $m;
	print MONTEXTE2 $m . "\n";
	print MONTEXTE2 $point . "\n" if $point ne '';
    }

    close(MONTEXTE2);
    close(MONTEXTE);

}
